### ISSUE TITLE
Display issue on small device

### ISSUE THREAD

**Issue by dredaz** [yo35/rpb-chessboard#101]
Thank you for this great plugin.

I used scroll left for **Position of the navigation board** to display chess article. It's perfect on laptop, but on small-screen phone, there's an issue:
   + The analysis board is gone, only chessboard with navigation toolbar is  kept.
   + Whenever I tap on navigation button (forward, backward), it trigger to call out phone's virtual keyboard.

I have a small suggestion: the chessboard with navigation toolbar would appear above and stay on top; the scrollable analysis board would appear below. This arrangement would fit best to smartphone. When it's on big screen, just keep it default.
Or else, please add some setting for **Small-screen devices** that we can choose how the board would appear on small-devices.

Just some suggestions,
Thank you and Bestwishes.

**Comment by yo35** [comment]
Hi,
Version 5.1.3 should improve rendering on small -screen devices. Let me know whether or not it is OK for you now.

**Comment by dredaz** [comment]
Hi,

The look is perfect now. Thank you for looking into it. But when I tap a
move, or a button on navigation bar, it still call out keyboard.

**Comment by chessclubblog** [comment]
Where to download v 5.1.3

**Comment by yo35** [comment]
Hi,
It's available on the plugin page on WordPress.org: https://wordpress.org/plugins/rpb-chessboard/

**Comment by chessclubblog** [comment]
Yes
I have installed it already
Commented there by mistake
Anyways thanks a lot

**Comment by yo35** [comment]
Hi,
The keyboard popup issue is fixed in RPB Chessboard version 5.1.5 (just released).

**Comment by dredaz** [comment]
It's amazing!
Thank you and best regards!

2018-01-01 19:45 GMT+07:00 Yoann Le Montagner <notifications@github.com>:
