### ISSUE TITLE
Pop up Board problem

### ISSUE THREAD

**Issue by Seb-Fe** [yo35/rpb-chessboard#102]
Hi!

I haven't been uploading my site for some months, and now I realized that the pop-up board doesn't show when I click on a move. For example: [(https://estudiandoajedrez.com/analice-partidas-y-ganele-a-la-sveshnikov/)] Also, when I double click on any move, the page moves to the game header.

I just upgrade my theme (Ribosome) and install a new plugin (Autoptimize), but I tried to deactivate the plugin and reinstall RPB Chessboard, but the problem persist. I don't know if the problem was there before doing that.

There is a known incompatibility? Do you know what can I do?

Thanks!

**Comment by yo35** [comment]
Hi,
This is probably a conflict of some kind, but with the JavaScript cache, it is very to understand what happens. Could you try to disable the Autoptimize plugin just for the moment?

**Comment by Seb-Fe** [comment]
Done :)

**Comment by yo35** [comment]
There is still another cache plugin enabled. W3 Total Cache I guess.

**Comment by Seb-Fe** [comment]
You are right, and now it seems to work... So it was W3 Total Cache the plugin that create the conflict?

I check activating Autoptimize again and it seems to work.

**Comment by yo35** [comment]
Apparently there is a problem with W3 Total Cache, but it may depend on the settings of the plugin. I was not able to reproduce the problem on my test website...
By the way, I think you should not use both W3 Total Cache and Autoptimize at the same time, as both plugins do more or less the same thing.

**Comment by Seb-Fe** [comment]
Yes, I know. I was sure I disabled the W3 plugin. Only when you mentioned it I find I was wrong..

Thanks for the help!
