### ISSUE TITLE
Keyboard pop up when using mobile 

### ISSUE THREAD

**Issue by wael96** [yo35/rpb-chessboard#104]
Dear Developers,
Thank you for developing such nice chess viewers, but i try to view from the mobile, there seems something wrong for me as the mobile keyboard always pop up when i click "next move" button![Before](https://i.imgur.com/rNAnRg9.png)
![After](https://i.imgur.com/NTHfBlJ.png)
Could you guide me what should I do to prevent keyboard pop up?
Thank you and have a nice day!

**Comment by yo35** [comment]
Hi,
This is indeed a bug I have to work on. Also reported in #101.

**Comment by yo35** [comment]
Hi,
Fixed in version 5.1.5 (just released).
