### ISSUE TITLE
Navigation board slide upside automatically 

### ISSUE THREAD

**Issue by wael96** [yo35/rpb-chessboard#111]
Dear Sir, 
I tried to set my position of navigation board in the following way,
![3](https://user-images.githubusercontent.com/7922775/34624269-a795f4c6-f28f-11e7-86eb-0dce507bb83b.png)
At first, everything goes well, but something wrong went on from here(after 6...Nc6)
![1](https://user-images.githubusercontent.com/7922775/34624300-cc5e0438-f28f-11e7-8297-f01f51fd8909.png)

When the move 7.Qf2 played, the screen slide up automatically like this.
![2](https://user-images.githubusercontent.com/7922775/34624311-d0c6b128-f28f-11e7-89c2-4764e9169c77.png)

Same happened as well in all the following moves...

As in mobile user-interface,
each time when I clicked "next move" button, the annotation seems do not displayed at the proper position.

Is this a bug or my error?

Thank you and have a nice day!

**Comment by yo35** [comment]
Should be fixed in version 5.1.6 (just released).
