### ISSUE TITLE
Cache without using filesystem

### ISSUE THREAD

**Issue by paulschreiber** [yo35/rpb-chessboard#116]
WordPress VIP support will not allow this plugin to be used until this issue is addressed:

## helpers/cache.php
This cache mechanism must be rewritten as it relies on the filesystem

**Comment by yo35** [comment]
In RPB Chessboard, caching is used to store some dynamically generated CSS code, that is not likely to change often, but that cannot be defined in a fully static way. The idea is to avoid having to much CSS inlined each time a page is generated.

Do you have a suggestion to achieve this in a more proper way?

**Comment by paulschreiber** [comment]
WordPress has its own built-in caching method. You can use `wp_cache_set()` / `wp_cache_get()` for caching.

Complete documentation is here:
https://codex.wordpress.org/Class_Reference/WP_Object_Cache

**Comment by yo35** [comment]
But WP_Object_Cache is not intended for file caching, am I wrong?

**Comment by paulschreiber** [comment]
WP_Object_Cache is a key/value store. You can use it for many things. I've created a PR uses the object cache.

If you're concerned about inlining the CSS, I can rewrite this so we generate distinct, cacheable URLs for each cached CSS blob and enqueue them.

**Comment by yo35** [comment]
It seems that the function `wp_add_inline_style( $handle, $data )` does nothing if `wp_enqueue_style( $handle, ...)` has not been called previously, **with the same `$handle`**. I've fixed your PR to account for this pitfall in the WP API...
