### ISSUE TITLE
AJAX: Don't write to filesystem

### ISSUE THREAD

**Issue by paulschreiber** [yo35/rpb-chessboard#118]
WordPress VIP support will not allow this plugin to be used until this issue is addressed:

## models/ajax/removepiecesetsprite.php
Line 43, file system writes are forbidden.

**Comment by paulschreiber** [comment]
It looks like this file/class is never used. Is that correct? Can it be removed?

**Comment by yo35** [comment]
This class is used to implement an AJAX call, which is related to the process I've just described in #117.

Basically, when an attachment is removed, if it has been used to generate a sprite image as described in #117, then the sprite image must be removed as well. This is what is done by the function `run()` in this class.

**Comment by yo35** [comment]
The class `models/ajax/removepiecesetsprite.php` has been removed with the refactoring achieved for #117.
