### ISSUE TITLE
Strings must be escaped

### ISSUE THREAD

**Issue by paulschreiber** [yo35/rpb-chessboard#121]
WordPress VIP support will not allow this plugin to be used until this issue is addressed:

## templates/
All the files are missing a proper escaping of strings.

## wp/scripts.php
Line 126, missing escaping

**Comment by yo35** [comment]
`htmlspecialchars` has been replaced with the WP-escaping functions in master. I've also add escaping the missing points you pointed at.
The localized strings still need to be escaped.

**Comment by yo35** [comment]
Fixed in master
