### ISSUE TITLE
JavaScript: HTML not built with DOM manipulation

### ISSUE THREAD

**Issue by paulschreiber** [yo35/rpb-chessboard#122]
WordPress VIP support will not allow this plugin to be used until this issue is addressed:

## js/rpbchess-ui-chessboard.js
* Line 298, HTML should be built using DOM manipulation when using arbitrary variables. See https://vip.wordpress.com/2015/03/25/preventing-xss-in-javascript/
* Line 313 (`buildContent` function), HTML should be built using DOM manipulation when using arbitrary variables. See https://vip.wordpress.com/2015/03/25/preventing-xss-in-javascript/
* Line 975, HTML should be built using DOM manipulation when using arbitrary variables. See https://vip.wordpress.com/2015/03/25/preventing-xss-in-javascript/

## js/rpbchess-ui-chessgame.js
* Line 425, HTML should be built using DOM manipulation when using arbitrary variables. See https://vip.wordpress.com/2015/03/25/preventing-xss-in-javascript/
* Line 605 (`refresh` function), HTML should be built using DOM manipulation when using arbitrary variables. See https://vip.wordpress.com/2015/03/25/preventing-xss-in-javascript/
* Line 799 (`buildErrorMessage` function), HTML should be built using DOM manipulation when using arbitrary variables. See https://vip.wordpress.com/2015/03/25/preventing-xss-in-javascript/
* Line 873 (`playerNameHeader` function), HTML should be built using DOM manipulation when using arbitrary variables. See https://vip.wordpress.com/2015/03/25/preventing-xss-in-javascript/
* Line 899 (`datePlaceHeader` function), HTML should be built using DOM manipulation when using arbitrary variables. See https://vip.wordpress.com/2015/03/25/preventing-xss-in-javascript/
* Line 923 (`annotatorHeader` function), HTML should be built using DOM manipulation when using arbitrary variables. See https://vip.wordpress.com/2015/03/25/preventing-xss-in-javascript/

**Comment by paulschreiber** [comment]
Work in progress on PR #124.

**Comment by paulschreiber** [comment]
@yo35 This is ready for review.

**Comment by yo35** [comment]
@paulschreiber:
I'm currently working on this. `rpbchess-ui-chessboard.js` should be OK now, `rpbchess-ui-chessgame.js` is still under work.

I chose to not merge your PR #124 as I want to take the opportunity to clean the rendering code a little bit. However, I've re-used part of your code for the refactoring, so thanks for your work.

I still make use of `.innerHTML` at some places in the code. However, the DOM built this way is now properly sanitized. I use https://www.npmjs.com/package/sanitize-html for the sanitization (see function `sanitizeRichText` in `rpbchess-ui-chessgame.js` for more details).

**Comment by yo35** [comment]
Fix released with version 5.3.
