### ISSUE TITLE
problem with the display

### ISSUE THREAD

**Issue by foufouboy** [yo35/rpb-chessboard#127]
When I insert a window to show the chessboard he shows me this : 
![image](https://user-images.githubusercontent.com/37068293/36969186-1e4c79c0-2065-11e8-9b1d-9ca0c88b07e3.png)

**Comment by IssaLeBoloss** [comment]
Any one can help me please ?

**Comment by yo35** [comment]
Hi,
Which WordPress theme are you using? What is the address of your website?

**Comment by yo35** [comment]
No news for more than 2 years... closing the issue.
