### ISSUE TITLE
clicking moves resets page back to the top, every time ! 

### ISSUE THREAD

**Issue by richiwalt** [yo35/rpb-chessboard#128]
Greetings,

I will admit, it has been a while since I have looked at the WordPress rpb chessboard plugin.

Recently I have returned to using my chess website. I am noticing that if I mouse click on a move, the page resets itself to the top ...  It’s very annoying to scroll back down the page to where  you were before - only to click the next move and repeat the process all over again. 

I am running the latest WordPress version (version  4.9.4 )  and the latest RPB Chessboard version 5.2. (Unless something is stuck in a long-ago invite to a beta testing program back when you introduced keyboard shortcuts or something). 

I am running with the "floating chessboard" mode where clicking a move for the first time pops open the board ... and additional clicks advance the moves.   Now if I use arrow keys to advance, I do not see this problem ... however, I am accustomed to mouse-clicking a move while reading along in the comments of a game.   

Is this reset-to-top-of-page behavior normal ?  Is there a fix for this issue?  I have tried several themes to see if that was the issue - problem exists in all themes. 

thanks for any info,

Richard

**Comment by pri40** [comment]
I agree with richiwalt!
Je vais continuer en Français, parce que c'est plus facile....
Le comportement décrit par richiwalt est exact.
C'est dommage, parce que le plugin est formidable.
Dans la version antérieure, je n'avais pas ce comportement.
Cher Yoann Le Montagner, constatez-vous également le problème?
Faites nous un retour,
Merci

**Comment by yo35** [comment]
Hi,
Thank you guys for the report. I do notice the problem, I will investigate.

**Comment by yo35** [comment]
This problem appeared between versions 5.0.1 and 5.1, with the keyboard shortcut feature.

**Comment by yo35** [comment]
Fixed in version 5.2.1 (just released).

**Comment by pri40** [comment]
Thanks Mister Le Montagner,

Seems to be solved.

Nice job!

Regards

Pri40

 

De : Yoann Le Montagner <notifications@github.com> 
Envoyé : dimanche 8 avril 2018 10:57
À : yo35/rpb-chessboard <rpb-chessboard@noreply.github.com>
Cc : pri40 <richard.ph@free.fr>; Comment <comment@noreply.github.com>
Objet : Re: [yo35/rpb-chessboard] clicking moves resets page back to the top, every time ! (#128)

 

Closed #128 <https://github.com/yo35/rpb-chessboard/issues/128> .

**Comment by richiwalt** [comment]
Looks like this was closed about two hours ago.  The issue is set as resolved.  

I went to update the plugin ... but somehow it gets automatically updated without me doing anything (I’m a little confused by THAT).  Anyway, with version 5.2.1 the problem looks worse for me.  

Now it resets the page to near the bottom - every time!   And the page updates slower.  


I’ve checked multiple browsers as well.  Safari and Chrome.

**Comment by yo35** [comment]
@richiwalt What is the address of your website?

**Comment by richiwalt** [comment]
Upon further inspection...

Looks like it is trying to make the mouse clicked move be at the very top,of the page.  Sometimes this guess is correct, but most times it’s off and the clicked move is not visible as it scrolled the page down too far.   My website is not visible to the public because of book copyright issues and requires admin to be logged in.  But the guess as to where to compute “top of page” looks off by more than just the admin navigational bar thickness.  

Regardless ... I was really hoping it would not scroll the page at all and leave the page at user’s last set position.   

As it is, it remains still a big with current behavior.
