### ISSUE TITLE
Ugly bug in PGN download

### ISSUE THREAD

**Issue by Glareanus** [yo35/rpb-chessboard#130]
Downloading a game with diagram results in the additional string
"<div class="rpbui etc.>"
in the PGN file.
This will destroy the whole PGN file.
An ugly bug that should be fixed as soon as possible!
Greetings

**Comment by yo35** [comment]
Hi,
As of version 5.3 (just released), you must use `[#]` instead of `[pgndiagram]`. The `[#]` is the "standard" tag used by chess softwares (e.g. Chessbase) for diagrams. As a result, you will no longer get a `<div ...></div>` tag when downloading a PGN file (you will get the standard `[#]`).

**Comment by Glareanus** [comment]
Thanks for your efforts.

Greetings from Switzerland:

Walter Eigenmann
078 940 84 11


Yoann Le Montagner <notifications@github.com> schrieb am Sa., 26. Mai 2018,
19:29:
