### ISSUE TITLE
tag [pgndiagram ] not run with [pgn_compat url=...

### ISSUE THREAD

**Issue by italianplayer** [yo35/rpb-chessboard#131]
Hi
tag [pgndiagram ] is fine with pgn load inline

[pgn_compat] 
....15. Qxa4 Bd7 16. Ra2 Rae8 17. Qa6 {[pgndiagram] Morphy took twelve...

but not run with url pgn
[pgn_compat url="mygame.pgn"....

thanks for all

**Comment by yo35** [comment]
Hi,
As of version 5.3 (just released, you must use `[#]` instead of `[pgndiagram]`. The `[#]` is the "standard" tag used by chess softwares (e.g. Chessbase) for diagrams. `[#]` should work with both inline PGN ang PGN files passed through the `url=...` attribute.

**Comment by italianplayer** [comment]
Hi,
with version 5.3

inline 
{[# ] }  work
{[# square_size=24] } not work

with url=...
{[# ] }  not work
{[# square_size=24] } not work

thanks

**Comment by italianplayer** [comment]
Hi,
this is my **test inline**  http://wpdev2.altervista.org/rpbchess/ with
[pgn_compat] 
...Ra2 Rae8 17. Qa6 {[#] Morphy took...
[/pgn_compat]
1)what do you mean with 
> 
It is still possible to define the attribute square_size=24 on the [pgn][/pgn] tag, in order to customize the size of the diagrams.
>
2) is it not possible to make the big main diagram and the small intermediate diagrams? (square_size=24)

this is my test **pgn dataurl** http://wpdev2.altervista.org/test-rpbviewer-dataurl/
with 18. Bxb4 { [# ] }
[White "Pillsbury, Harry"]
[Black "Chigorin, Mikhail"]
[Date "1899.??.??"]
[Result "0-1"]
[Event "London"]
[Site "London"]
[Round "27"]
[UTCDate "2016.10.24"]
[UTCTime "19:41:27"]
[Variant "Standard"]
[ECO "D07"]
[Opening "Queen's Gambit Refused: Chigorin Defense, Main Line"]
[Annotator "ItalianPlayer"]

1. d4 d5 2. c4 Nc6 3. Nf3 Bg4 4. e3 e6 5. Nc3 Bb4 6. Qb3 Bxf3 7. gxf3 Nge7 8. Bd2 O-O 9. Bd3 Rb8 10. cxd5 Nxd5 11. O-O-O Bxc3 12. Bxc3 b5 13. Bd2 Rb6 14. Rdg1 a5 15. f4 f5 16. Rg3 a4 17. Qd1 Ncb4 18. Bxb4 { [# ] } Nxb4 19. Rhg1 Rf7 20. Bb1 a3 21. bxa3 Nd5 22. Qb3 b4 23. axb4 Rxb4 24. Qd3 c5 25. dxc5 Qa5 26. Bc2 Qxa2 27. f3 Rc4 28. R3g2 Rd7 29. c6 Rxc6 30. Qd4 Qa3+ 31. Kd2 Rxc2+ 32. Kxc2 Nxe3+ 33. Kb1 Rxd4 34. Rxg7+ Kf8 35. Rg8+ Ke7 0-1

**Comment by yo35** [comment]
Hi,
Regarding your first point: if you want to have a custom size for the diagrams in your game, you can define the attribute `square_size=...` in the pgn_compat tag. For instance:
```
[pgn_compat square_size=24]
...
[/pgn]
```
This will affect both the navigation board (the one with the buttons) and the diagrams within the moves. Currently, it is not possible to change the size of the diagrams without affecting the size of the navigation board (although it was possible to do so with the former `[pgndiagram]` tag. I was not sure this feature was actually used, so I removed it, but it may be relevant to restore it in some way.

Regarding your problem with diagrams not appearing: diagrams are inserted by the plugin where the following exact three characters are found: `[#]`. In your text, it seems there is a space character between `#` and `]`. This space character must be removed.

**Comment by italianplayer** [comment]
1) ok for exact three characters [#]
http://wpdev2.altervista.org/test-rpbviewer-dataurl/

2) I wait your fix to change the size of the board without affecting the size of the navigation board

thanks

**Comment by yo35** [comment]
As of RPB Chessboard 7.2 (just released), it is possible to set different sizes for the navigation board and for the diagrams.
