### ISSUE TITLE
HTML string construction in piecesets.php

### ISSUE THREAD

**Issue by paulschreiber** [yo35/rpb-chessboard#132]
WordPress VIP reviewed version 5.3 of rpb-chessboard. They found the following:

In templates/adminpage/theming/piecesets.php there's some HTML string construction that needs swapping out:
```
$('.rpbchessboard-coloredPieceButton-' + coloredPiece, form).empty().append('<img src="' + attachmentURL + '" width="64px" height="64px" />');
```

**Comment by yo35** [comment]
Fixed in version 5.3.1 (just released).
Thanks for your help in improving the code safety of the plugin.
