### ISSUE TITLE
Possible bug: on small boards, animated pieces move from outside their squares.

### ISSUE THREAD

**Issue by squarology** [yo35/rpb-chessboard#136]
For example, if you go to https://chess.academy/test/ and click on the forward arrow one time so that the first move is played, it looks like the c-pawn moves from c1 or even outside the board. 

It's only on the small boards; it doesn't happen on the bigger boards. I don't know if this is a bug within the plugin or if maybe my theme is causing the issue. I have a feeling it's my theme but I want to be sure. Perhaps someone else could try to reproduce it on his website?

Thank you very much.

Edit: I'm using Chrome but I also tested in Firefox and I get the same result: the pieces do not animate from their original squares on smaller boards (when I resize the window down to what a smartphone would be, for example).

**Comment by yo35** [comment]
Fixed in version 5.4.1.
