### ISSUE TITLE
rpb-chessboard and Gutenberg

### ISSUE THREAD

**Issue by smittySKHG** [yo35/rpb-chessboard#137]
Hi,

rpb-chessboard seems not to be integrated in the new Gutenberg-editor (https://wordpress.org/gutenberg/) yet, which becomes mandatory with next release of WordPress. 

Right?

Walter

**Comment by yo35** [comment]
Hi,
Right, some work has to be done to get RPB Chessboard properly work with Gutenberg:
- the chess position editor currently plugged to TinyMCE has to be plugged to the new page/post editor,
- there is a bug with `[pgn][/pgn]` tags if the content between these tags spans over several lines (which should be the case most of the time).

**Comment by maximuss22** [comment]
Hi
In a same wordpress page I use 2 chess plugin: pgn4web and RPB chessboard.
It works and view perfectly. 

If I active plugin Gutemberg, I view this error in output:

Error while analysing a PGN string.
Unrecognized character or group of characters.
Occurred at position 0:
</p> <p>[Event "Segrate 2017-2018"]<br />...
^

If I deactive Gutemberg Plugin I view tha page fine

bye Max

**Comment by yo35** [comment]
The issue re-appeared in Gutenberg version 4.1.1.

**Comment by yo35** [comment]
Fixed (again) in 5.4.3.
