### ISSUE TITLE
Read More tag needs functionality

### ISSUE THREAD

**Issue by PerceiveEnergy** [yo35/rpb-chessboard#140]
Trying to add the  tag in the form of a comment won't work on the homepage.

**Comment by yo35** [comment]
Sorry, I don't understand your question. Can you explain the problem a bit further?

**Comment by PerceiveEnergy** [comment]
Make the "Continue Reading..." feature available inside of a PGN.

**Comment by yo35** [comment]
You cannot put this tag "Continue reading..." within a PGN. Before or after is OK, but within the PGN, it will not work.
