### ISSUE TITLE
The movelist is not displayed if rpb chessboard used inside another shortcode

### ISSUE THREAD

**Issue by dredaz** [yo35/rpb-chessboard#141]
Hi Yoan,

I used third-party shortcode generator to create toggle, tab, arcordion. Problem is, when I put rpbchessboard in side these shortcode, the move list would not appear, the board is still displayed as ussual.

The shortcode usage is like this:
[accordion title="Click to show analysis" load="hide"][pgn_compat]
pgn content
[/pgn_compat][/accordion]

I attach a picture, the upper part is rpbchessboard while display normally, the lower is rpbchessboard while inserted inside an another shortcode.
![screenshot 2018-08-20 13 14 06](https://user-images.githubusercontent.com/33801681/44323391-f0a3cf00-a47b-11e8-8644-2c26ae918707.png)

Warm regards,

**Comment by yo35** [comment]
Hi,
Can you precise the name of the plugin used for the `[accordion]` tag, and may be a link to a page which shows the problem? That would help to have it solved.

**Comment by dredaz** [comment]
Hi, sorry for the late reply. I double checked to avoid making any anoyments to you.
I used publisher theme from Better Studio and the bult-in shortcode first. May I send you the theme package to investigate? I also make test to some other shortcode plugins:

[Shortcodes by Angie Makes
](https://wordpress.org/plugins/wc-shortcodes/)
[Magee shortcodes
](https://wordpress.org/plugins/magee-shortcodes/)
[Site Origin widgets by Codelights
](https://wordpress.org/plugins/codelights-shortcodes-and-widgets/)
[Shortcodes Ultimate
](https://wordpress.org/plugins/shortcodes-ultimate/)

When put rpbchessboard in tab1, thing was fine, but with other tabs, the movelist disappeared!
I also test with shortcodes that generate modal box (Magee shortcodes; Site Origin widgets by Codelights; Shortcode Ultimate), the movelist also disappeared in 2/3 plugin.

Test link: https://dochess.work/uncategorized/3104/
Please tell me if there is anything I can assist.
Thank you and warm regards

**Comment by yo35** [comment]
Fixed in version 5.4.2.
