### ISSUE TITLE
Weird characters appear on the front-end

### ISSUE THREAD

**Issue by paulewhite** [yo35/rpb-chessboard#147]
Hi, when I see the game on the front-end some weird characters appear replacing the original ones in the pgn file.

For example: 
7. Nc2 $5
becomes:
7.Nc2 !?

The problem seems related to the $ character.

I am using the latest version of the plugin with WP 5.1 but the problemalso appeared before the update.

**Comment by yo35** [comment]
Hi,
That's the expected behavior, as defined by the [PGN standard](http://www.saremba.de/chessgml/standards/pgn/pgn-complete.htm): see for instance https://en.wikipedia.org/wiki/Numeric_Annotation_Glyphs for more details regarding this feature.
