### ISSUE TITLE
Support for 960 chess (Fischer random chess)

### ISSUE THREAD

**Issue by dawidziolkowski** [yo35/rpb-chessboard#15]
Hi, i propose including the ability to set the starting positions of 960's chess in FEN (some options are described in Wiki http://en.wikipedia.org/wiki/Forsyth-Edwards_Notation#FEN_adjustment_for_chess_variants_like_Chess960) so it would be possible to show 960 games. Ew. pgn4web supports as well X-FEN as Schredder-FEN, maybe it would be useful: https://code.google.com/p/pgn4web/wiki/PGN_Support#about_Chess960

**Comment by drgibbon** [comment]
Just wondering about the viability of chess960 in rpb-chessboard these days, considering that the [Unofficial Chess960 World Championship](http://www.frchess.com/) is on :)

By the way, X-FEN is not necessary for the display of chess960 games from the start (standard FEN can handle all 960 starting positions). X-FEN is only needed in cases which might arise in actual play where it's ambiguous which rook is the castling rook (although these positions must be quite rare). There's an [X-FEN example here](https://en.wikipedia.org/wiki/X-FEN#X-FEN_example).

**Comment by yo35** [comment]
Hi,
Unfortunately, chess 960 is still not available in RPB Chessboard. However, I still plan to implement it in a future version -- especially if events such as the one you mentioned become more frequent.
