### ISSUE TITLE
Custom starting position PGN bug

### ISSUE THREAD

**Issue by johngt109** [yo35/rpb-chessboard#150]
Almost all PGN with custom starting position starting doesn't work. For example, the following PGN doesn't work:
[pgn]
[FEN "3b4/8/8/2p3NK/1pP5/1P6/5k2/8 b - - 0 1"] [SetUp "1"] 1...Bxg5 {Black exchanges his bad Bishop with a good Knight.} 2. Kxg5 Ke2 {King tries to reach b3.} 3. Kf5 {King tries to reach c5.} 3... Kd2 4. Ke5 Kc2 5. Kd5 Kxb3 6. Kxc5 Kc3 7. Kd5 b3 {This pawn is going to be a Queen at b1.} 8. c5 {This pawn is going to become a Queen at c8.} 8... b2 9. c6 b1=Q {Black will stop the opponent pawn at c6 and will win the game with his Queen.} *[/pgn]
Thanks for your time.

**Comment by yo35** [comment]
Hi,
I cannot reproduce the problem, your game is displayed with no error in my test environment:

![screenshot](https://user-images.githubusercontent.com/5740068/55899489-38bb6180-5bc5-11e9-9986-98e438f02c53.png)

Can you give more details about the error you encounter?

**Comment by johngt109** [comment]
Hi, and thank you so much for your quick response.
It used to work fine but for some reason, I encounter this problem. Instead, of the game it is displayed the following text: Error while analyzing a PGN string.
Unrecognized character or group of characters.
Occurred at position 0:
[FEN "1r2b3/1k1p3p/1p2p1p1/8/3PPP2/2P1B3/...
^

**Comment by yo35** [comment]
Hi,
You must have a line-break after each header in the PGN text. That is:
```
[pgn]
[FEN "3b4/8/8/2p3NK/1pP5/1P6/5k2/8 b - - 0 1"]
[SetUp "1"]
1...Bxg5 {etc} *
[/pgn]
```
And not:
```
[pgn]
[FEN "3b4/8/8/2p3NK/1pP5/1P6/5k2/8 b - - 0 1"] [SetUp "1"] 1...Bxg5 {etc} *
[/pgn]
```

**Comment by johngt109** [comment]
You are right. Merci beaucoup.
