### ISSUE TITLE
Rookmove doesn't work

### ISSUE THREAD

**Issue by bonaventura61** [yo35/rpb-chessboard#153]
Hi there, 

in this pgn-file the move 26. Rae1 is not correctly processed:  

[pgn_compat]
[Event "SBBL MM 1. Bezirksliga 18/19"]
[Site "Solingen"]
[Date "2019.01.27"]
[Round "5.11"]
[White "XXX"]
[Black "YYY"]
[Result "1-0"]
[ECO "C41"]
[WhiteElo "1661"]
[BlackElo "1484"]
[PlyCount "77"]
[EventDate "2018.09.09"]
[EventType "team"]
[EventRounds "9"]

1. e4 d6 2. d4 Nf6 3. Nc3 Nbd7 4. Nf3 e5 5. Bc4 Be7 6. h3 c6 7. O-O b5 8. Bd3 O-O 9. Ne2 Re8 10. Ng3 Nf8 11. dxe5 dxe5 12. Nxe5 Qc7 13. f4 Bc5+ 14. Kh1 Bd6 15. c3 Bxe5 16. fxe5 Qxe5 17. Bf4 Qe6 18. e5 Nd5 19. Bf5 Qe7 20. Qg4 Nxf4 21. Rxf4 Ng6 22. Re4 Bxf5 23. Nxf5 Qe6 24. h4 h5 25. Qxh5 Qd5 26. Rae1 Nxe5 27. Qg5 g6 28. Nh6+ Kh7 29. Rxe5 Rxe5 30. Rxe5 Qd1+ 31. Kh2 Rf8 32. Ng4 Qd6 33. h5 Kg8 34. Nf6+ Kg7 35. h6+ Kh8 36. g3 Qd8 37. Qf4 Qd1 38. Ng4 Rd8 39. Qf6+ 1-0
[/pgn_compat]

Wordpress 5.1.1
RPB-Chessboard 5.6

Please fix. TIA, Marius

**Comment by yo35** [comment]
Fixed in version 5.6.1 (just released)

**Comment by bonaventura61** [comment]
Wow, you’re fast! Thanks so much!

**Comment by bonaventura61** [comment]
Sorry, didn’t do the job. Please look here: http://isolani.net/fraenzel-soechting/

**Comment by bonaventura61** [comment]
Sorry, that was a cache-problem.
