### ISSUE TITLE
jquery wasn't generated in my custom template

### ISSUE THREAD

**Issue by estruth** [yo35/rpb-chessboard#154]
dear sirs please look at my homepage with a own template. The url is 
https://www.schachklub-wiehre.de/ralfs-taktische-meisterleistung/
all srcipts with jquery wasn't generated as on your site as
<script src='https://rpb-chessboard.yo35.org/wp-includes/js/jquery/jquery.js?ver=1.12.4'></script>
Why? Thanks in advance. best regards edi

**Comment by yo35** [comment]
Hi.
This problem comes from the fact that your theme does not include jQuery by default (which is rightful). The plugin wrongly assumes that jQuery is already included when trying to render the chessboard/chessgames.

To cut a long story short, this is a bug of the plugin, I have to fix it.

**Comment by yo35** [comment]
Fixed in plugin version 5.6.2 (just released).
