### ISSUE TITLE
Error while analysing a PGN string.

### ISSUE THREAD

**Issue by Hellchess** [yo35/rpb-chessboard#155]
Why is this a problem again? It's not so long since I check that the games were ok, but now there's a conflict again. What is the solution?

**Comment by Hellchess** [comment]
Error while analysing a PGN string.
Unrecognized character or group of characters.
Occurred at position 0:
</p> <p>[Event "Xtracon Chess Open 2018"]...
^

**Comment by yo35** [comment]
Hi,
Maybe the line break is missing after the event header. It should be:
```
[Event "Xtracon Chess Open 2018"]
[Site "Somewhere"]
...
```
And not:
```
[Event "Xtracon Chess Open 2018"] [Site "Somewhere"] ...
```

**Comment by GaborHorvath11** [comment]
I have the same error message: 

Error while analysing a PGN string.
Unrecognized character or group of characters.
Occurred at position 0:
</p>
 <p>[Event "Dorset Open 2017"]<br />...
^

And this is my PGN, straight from Chessbase:

[pgn]

[Event "Dorset Open 2017"] 
[Site "?"]
[Date "2017.10.15"]
[Round "4"]
[White "Horvath, Gabor"]
[Black "Merry, Alan"]
[Result "1-0"]
[ECO "B01"]
[Annotator "Gabor"]
[PlyCount "57"]
[SourceVersionDate "2013.05.04"]

1. e4 d5 2. exd5 Qxd5 3. Nc3 Qd8 4. d4 g6 5. Nf3 Bg7 6. Bc4 Nf6 7. O-O O-O 8.
h3 $6 (8. Ne5 Nbd7 9. Re1 Nxe5 10. dxe5 Qxd1 11. Rxd1 Ng4 12. f4 $16) 8... b6
9. Re1 Bb7 10. Bg5 Nc6 11. a3 $6 (11. Qd2 e6 12. Rad1 Ne7 13. Ne5) 11... h6 12.
Bf4 e6 13. Qd2 Ne7 14. Ne5 Nf5 15. Rad1 Qe7 $4 (15... Kh7 16. Bh2 Qe7) (15...
Rc8 16. Nxf7 $6 Rxf7 17. Bxe6 Qf8 18. Qd3 Kh7) 16. Nxg6 fxg6 17. Bxe6+ Kh7 18.
Bxf5 Qd8 19. Bd3 Nd5 20. Bg3 Nxc3 21. bxc3 Qd7 22. Be5 Rad8 23. Bxg7 Qxg7 24.
Be4 Bc8 25. Qe3 Rf6 26. Qg3 Rdf8 27. Re2 R8f7 28. Rde1 Qf8 29. Bd5 1-0

[/pgn]

Please advise. Many thanks!

**Comment by yo35** [comment]
You may have a problem with the line breaks in your PGN. Still the parser should be more robust to this kind of issues. I'll push a fixed.

**Comment by yo35** [comment]
Hi,
It should be better with RPB Chessboard version 5.6.5 (just released). Let me know if this is not the case.
