### ISSUE TITLE
diagram e squaresize

### ISSUE THREAD

**Issue by italianplayer** [yo35/rpb-chessboard#156]
Hi, 

[pgn_compat square_size=24] ...[/pgn]
This will affect both the navigation board (the one with the buttons) and the diagrams within the moves.
Currently, it is not possible to change the size of the diagrams without affecting the size of the navigation board (although it was possible to do so with the former [pgndiagram] tag. 

I hope you found the solution to view the smaller secondary diagrams than the main one.
this allows a better reading of the page

thanks for everything

**Comment by yo35** [comment]
Hi,
Obviously I need to improve how diagram size is managed, in order to allow different default size for 1) the navigation board, 2) the diagrams withing games, and 3) the standalone diagrams.

**Comment by yo35** [comment]
As of RPB Chessboard 7.2 (just released), it is possible to set different sizes for the navigation board, for the diagrams within games, and for the standalone diagrams.
