### ISSUE TITLE
custom start move in pgn

### ISSUE THREAD

**Issue by Ponticulus** [yo35/rpb-chessboard#157]
Love this plugin.

Is it possible to have a whole game in pgn but when the page loads let the display board start at a custom move? And then be able to play through the game backwords and forwards?

Or do I have to use fen and only be able to play the game forward from there?

something like this:

[pgn startAt=10 navigation_board=floatLeft]

[Event "Cellavision cup 2019"]
[Site "Lund, SWE"]
[Date "2019.08.03"]
[Round "5"]
[White "Magnus Spång"]
[WhiteElo "1751"]
[Black "Krister Jönsson"]
[BlackElo "2061"]
[Result "0-1"]

1. e4 c5 2. d4 cxd4 3. c3 d5 4. Qxd4 dxe4 5. Qxe4 Nc6 6. Nf3 Nf6 7. Qc2 g6 8. Bd3 Bg7 9. Bf4 O-O 10. Nbd2 Nd5 11. Bg3 Ndb4 0-1

[/pgn]

**Comment by yo35** [comment]
Hi,
This is not currently possible, although this is an interesting idea. I'll try to implement that in a future version.

**Comment by Ponticulus** [comment]
Hi
Thank you for answer. 
Solved it by using to pages. 
Great plugin, thank you.
