### ISSUE TITLE
Parsing error

### ISSUE THREAD

**Issue by paulo101977** [yo35/rpb-chessboard#158]
Issue log:

```
Error while analysing a PGN string.
Unrecognized character or group of characters.
Occurred at position 1384:
... (18. Ne2 { /\Ne2-g3-f5/h5 }) 18... Qf6 19. R1e3 (1...
```

**Note:** website address to find out the problem:
https://www.chessgames.video/2019/10/chess-pgn-game-match-played-morphy-paul-vs-anderssen-adolf-in-match-morphy-anderssen-7-22-open-ruy-lopez-berlin-defence.html

**Comment by yo35** [comment]
Hi,
You may try without the characters `/\`. For instance:

```
... (18. Ne2 {Ne2-g3-f5/h5 }) ...
```

**Comment by paulo101977** [comment]
@yo35 Got it, without the Escape character!

**Comment by paulo101977** [comment]
@yo35 It worked! Thank you! I will query the database as there are possibly other character scapes in the code.

**Comment by paulo101977** [comment]
@yo35 I would like to help translating the plugin into Portuguese.

**Comment by yo35** [comment]
@paulo101977 instructions for Portuguese translation sent through private mail.
