### ISSUE TITLE
Not working in IE11

### ISSUE THREAD

**Issue by Ponticulus** [yo35/rpb-chessboard#159]
Hi!

Love the plugin

But. I do not see anyting in IE11.
Works fine in FF and chrome.

https://www.oskarshamnsschacksallskap.se/verksamhet/traning/intressanta-partier/johans-offer-festival/

**Comment by yo35** [comment]
Hi,
Unfortunately, IE (even version 11) has so many compatibility issues that it would require a significant amount of work to have the plugin work on this browser. As RPB Chessboard is developed and maintained on my spare time, for free, I cannot afford (and I want) to dedicate the corresponding effort to have the plugin work on IE11.

In other words, I don't want to compensate by myself the work that has not been done by Microsoft to meet the standards.

Still, things should be better with Edge.

**Comment by Ponticulus** [comment]
I completely understand.
Thank you for information.

/Magnus
