### ISSUE TITLE
Error while analysing a PGN string. Unrecognized character or group of characters. Occurred at position 0: 

### ISSUE THREAD

**Issue by rundllhan32** [yo35/rpb-chessboard#163]
Hello

I created my wordpress site 2 days ago. I want to analyze chess games on my website, but when i try to do in post i got this error but when i try to do this in pages it didn't happen. Can't i use this plugin on posts? 

I use the example PGN which is inside the plugin. 

[pgn]

[Event "1<sup>st</sup> American Chess Congress"]
[Site "New York, NY USA"]
[Date "1857.11.03"]
[Round "4.6"]
[White "Paulsen, Louis"]
[Black "Morphy, Paul"]
[Result "0-1"]

1. e4 e5 2. Nf3 Nc6 3. Nc3 Nf6 4. Bb5 Bc5 5. O-O O-O 6. Nxe5 Re8 7. Nxc6 dxc6 8. Bc4 b5 9. Be2 Nxe4 10. Nxe4 Rxe4 11. Bf3 Re6 12. c3 Qd3 13. b4 Bb6 14. a4 bxa4 15. Qxa4 Bd7 16. Ra2 Rae8 17. Qa6

{[#] Morphy bir sonraki hamle için 12 dakika düşündü. Büyük bir olasılıkla, kendi kendine kombinezonun mantıklı olduğunu ve her devam yolunda zorunlu hamlelerle bir kazancın olduğuna emin olmak istiyordu. }

17... Qxf3 !! 18. gxf3 Rg6+ 19. Kh1 Bh3 20. Rd1 ({Hayır} 20. Rg1 Rxg1+ 21. Kxg1 Re1+ -+) 20... Bg2+ 21. Kg1 Bxf3+ 22. Kf1 Bg2+

(22...Rg2 ! {daha çabuk kazanırdı. Örneğin} 23. Qd3 Rxf2+ 24. Kg1 Rg2+ 25. Kh1 Rg1#)

23. Kg1 Bh3+ 24. Kh1 Bxf2 25. Qf1 {Mutlak zorunlu} 25... Bxf1 26. Rxf1 Re2 27. Ra1 Rh6 28. d4 Be3 0-1

[/pgn]

**Comment by yo35** [comment]
Hi,
What is "this error" ?

**Comment by rundllhan32** [comment]
Error while analysing a PGN string.
Unrecognized character or group of characters.
Occurred at position 0:
<br /><br />[Event "1&lt;sup&gt;st&lt;/su...
^

That one. That was in the title.

**Comment by yo35** [comment]
Hi,
Everything is supposed to work fine, both in posts and in pages. Just copy-paste this in a "shortcode block" of the WordPress editor:

```
[pgn]

[Event "1st American Chess Congress"]
[Site "New York, NY USA"]
[Date "1857.11.03"]
[Round "4.6"]
[White "Paulsen, Louis"]
[Black "Morphy, Paul"]
[Result "0-1"]

1.e4 e5 2. Nf3 Nc6 3. Nc3 Nf6 4. Bb5 Bc5 5. O-O O-O 6. Nxe5 Re8 7. Nxc6 dxc6
8. Bc4 b5 9. Be2 Nxe4 10. Nxe4 Rxe4 11. Bf3 Re6 12. c3 Qd3 13. b4 Bb6 14. a4 bxa4
15. Qxa4 Bd7 16. Ra2 Rae8 17. Qa6

{[#] Morphy bir sonraki hamle için 12 dakika düşündü. Büyük bir olasılıkla,
kendi kendine kombinezonun mantıklı olduğunu ve her devam yolunda zorunlu
hamlelerle bir kazancın olduğuna emin olmak istiyordu. }

17... Qxf3 !! 18. gxf3 Rg6+ 19. Kh1 Bh3 20. Rd1 ({Hayır} 20. Rg1 Rxg1+
21. Kxg1 Re1+ -+) 20... Bg2+ 21. Kg1 Bxf3+ 22. Kf1 Bg2+

(22...Rg2 ! {daha çabuk kazanırdı. Örneğin} 23. Qd3 Rxf2+ 24. Kg1 Rg2+ 25. Kh1 Rg1#)
23.Kg1 Bh3+ 24. Kh1 Bxf2 25. Qf1 {Mutlak zorunlu} 25... Bxf1 26. Rxf1 Re2
27. Ra1 Rh6 28. d4 Be3 0-1

[/pgn]
```

I don't know why it has failed in your case. May be the copy-paste the PGN text went through an editor that adds some unexpected character to it (MS Word is the usual suspect).

**Comment by yo35** [comment]
Hi,
Is it OK now?

**Comment by yo35** [comment]
Let's assume the answer is yes => closing the issue.
