### ISSUE TITLE
Error while analysing a PGN string. Invalid move (Nc5). The position is not legal.

### ISSUE THREAD

**Issue by martin-r8s** [yo35/rpb-chessboard#164]
Hi,

thanks for your nice plugin. I usually upload pgn-files and everything works fine. Today, I had uploaded a file and one game gives the error: Error while analysing a PGN string.
Invalid move (Nc5). The position is not legal. Occurred at position 3805:
..."]  {[#]} 1.Nc5 $1 {bla1} 1...dxc5 {bla2}     ( {bl...

I found the game and pasted it into a [pgn][/pgn], result: I got the same error. I don't see an error in the pgn. Scid and Chessbase have no problems with the pgn.

Here is my pgn, I use the latest plugin 5.6.9 with wordpress 5.3.2

[pgn]
[Event "Moskau"]
[Site "?"]
[Date "1948.??.??"]
[Round "?"]
[White "Smyslov"]
[Black "Kottnauer"]
[Result "1-0"]
[EventDate "1948.??.??"]
[SetUp "1"]
[PlyCount "7"]
[SourceDate "2020.02.17"]
[FEN "1q2kb1r/1r1n1ppp/2Qpp3/8/N7/8/1PP2PPP/R1BR2K1 w q - 0 1"]

{[#]}
1.Nc5 $1 {bla1}
1...dxc5 {bla2}
    ( {bla3} 1...Rc7 2.Nxd7 Rxd7
        ( 2...Rxc6 3.Nxb8 {bla4} )
    3.Ra8 $18 {bla5} )
2.Bf4 $1 Bd6
    ( 2...Qxf4 3.Qc8+ Ke7 4.Qxb7 $18 {bla6} )
3.Bxd6 Rb6 {bla7} 4.
Qxd7+ $1 {bla8}
    ( 4... Kxd7 5.Bxb8+ {bla9} )
1-0
[/pgn]

**Comment by martin-r8s** [comment]
I also attached the file which gives the same error using  [pgn url="https://webside/wp-content/uploads/2020/04/error.pgn" game=0] 

[error.pgn](https://github.com/yo35/rpb-chessboard/files/4469868/error.pgn.txt)

**Comment by martin-r8s** [comment]
Ah, I have an error in my FEN string. The castling rights are wrong. It should be:
[FEN "1q2kb1r/1r1n1ppp/2Qpp3/8/N7/8/1PP2PPP/R1BR2K1 w k - 0 1"]

After that, I will get an error in the last line ( 4... Kxd7 5.Bxb8+ {bla9} ). 
It looks like that this is not a valid PGN from Chessbase, SCID also doesn't like a variation at the end of a game.

**Comment by yo35** [comment]
Hi,
The plugin does not allow to start a variation with `4... some-move` (i.e. a variation starting with move 4 for Black) if there is no move 4 for Black in the main line.
A workaround here is to repeat White's last move in the variation:

[pgn]
...
( 4.Qxd7+ Kxd7 5.Bxb8+ {bla9} )
[/pgn]
