### ISSUE TITLE
Changing the font sizes in RPB-Chessboard?

### ISSUE THREAD

**Issue by Glarean** [yo35/rpb-chessboard#165]
In RPB-Chessboard you can easily change the size of the diagrams. Is there a possibility to change the size of the FONTS (game and comments)?

**Comment by yo35** [comment]
The plugin is designed such that it inherits the font settings from the theme of the website whenever possible. The idea behind that is to enforce an homogeneous look between what is managed by the plugin on the one hand, and the rest of the page/post on the other hand. There is no setting to change that in the plugin configuration page, and my intent is to keep it that way.

One reason for that is the number of font settings that could be customized in HTML is countless: you can change the font, the font size, the font weight (bold, not bold, and all intermediate states), the font style (italic, oblique or normal); you can stretch the space between characters, you can underline them, overline them, strikethrough them; there are all the color settings, for the character themselves, for the background, for the character shadow... You can even make the text blink if you want! Providing a control panel for all these parameters is far beyond the amount of work I can dedicate to this plugin.

Another reason is that you can change these setting by injecting some custom CSS to your website. Use CSS selectors `.rpbchessoard-chessboard` and `.rpbchessoard-chessgame` to target respectively the isolated diagrams (inserted with [fen][/fen]) and the games (inserted with [pgn][/pgn]). For instance:

```
.rpbchessoard-chessboard {
  font-size: 200%;
}
```

... will increase the size of the font in the diagrams, and:

```
.rpbchessoard-chessgame {
  color: red;
}
```

... will make the text of games appear in red.

**Comment by Glarean** [comment]
Many thanks for your explications.

>The plugin is designed to inherit the font settings from the website theme whenever possible.  The idea behind this is to force a homogeneous look between what the plugin manages on the one hand and the rest of the page/post on the other.

I understand this idea well.
On the other hand, for layout and typographical reasons, it would often be very desirable if at least the **size** of the font could be changed in the plugin.

>One reason for this is that the number of font settings that can be adjusted in HTML is countless.

This is basically correct. But I have tried to change the font size in my WP text editor (Classic) using HTML tags. Unfortunately I did not succeed, the RPB-Plugin always reports an error...
So as I said, it would not be necessary to offer all the countless font formations in the plugin. It would be enough for many users, if **at least the font size** could be chosen freely...

Unfortunately I don't know CSS very well...

Thank you very much for your useful tool and best regards:

**Comment by yo35** [comment]
I will not implement the font size settings, since the same result can be achieved extremely easily with CSS. Just add:
```
.rpbchessoard-chessboard, .rpbchessoard-chessgame {
  font-size: 80%;
}
```
... to reduce the font size to 80% of its reference size.
