### ISSUE TITLE
RPB Chessboard utilization for OSSN ???

### ISSUE THREAD

**Issue by janlwi971** [yo35/rpb-chessboard#166]
I am looking to develop a chess diagram tool for OSSN platform :

 - https://www.opensource-socialnetwork.org/demo

Is it possible to adapt RPB Chessboard tool to OSSN (Open Source Social Network) platform ?

Thanks in advance.

**Comment by yo35** [comment]
Hi,

All the chess logic (including checking whever a move is legal or not, and FEN and PGN parsing) is implemented as a separate JavaScript library: https://www.npmjs.com/package/kokopu, and can be reused in other projects.

The rest remains tied to the WordPress environment for the moment. At some point, I would like extract the diagram and game rendering as well the chess logic, but this is not for tomorrow.

**Comment by yo35** [comment]
Diagram and game rendering is now available as an independent JavaScript/TypeScript library: https://www.npmjs.com/package/kokopu-react
