### ISSUE TITLE
Horde chess support

### ISSUE THREAD

**Issue by R-Peleg** [yo35/rpb-chessboard#167]
I would like to see the option to add [Variant "Horde"] to PGN games, for [Horde chess variant](https://lichess.org/variant/horde).

The rules are very similar to chess, except for the starting position and the fact that White has no king. This leads to failure when trying to use the [FEN] attribute of PGN since the rendering fails on the first move, which considered illegal.

**Comment by yo35** [comment]
Not that simple to implement, but why not...

**Comment by yo35** [comment]
Hi,
This is available in RPB Chessboard version 6.3.0 (just released).
