### ISSUE TITLE
problem with chess-fonts.css

### ISSUE THREAD

**Issue by Seb-Fe** [yo35/rpb-chessboard#169]
My site is trying to request /wp-content/plugins/rpb-chessboard/fonts/chess-fonts.css?ver=5.6.9 , but this .css file doesn't exist.

This file has been moved to another place? I need to do a redirection? It's a cache problem?

Thanks.

**Comment by yo35** [comment]
In RPB Chessboard version 5.7.0, this file has been removed (its content has been merged in `/wp-content/rpb-chessboard/css/rpbchess-ui-chessgame[.min].css`). I don't understand why you site tries to fetch a CSS file with `ver=5.6.9` if you have the latest version of the plugin.

**Comment by Seb-Fe** [comment]
I have the latest version (5.7.0). I purge every cache, but it keeps searching for this.

Do you think it will work if I redirect /wp-content/plugins/rpb-chessboard/fonts/chess-fonts.css?ver=5.6.9 to /wp-content/rpb-chessboard/css/rpbchess-ui-chessgame[.min].css, at least as a temporary solution until I find what happens?

**Comment by yo35** [comment]
You don't need to create a redirection since you probably already have the target `/wp-content/rpb-chessboard/css/rpbchess-ui-chessgame.min.css` (or `/wp-content/rpb-chessboard/css/rpbchess-ui-chessgame.css`) in your page.

What is your website?

**Comment by Seb-Fe** [comment]
https://estudiandoajedrez.com/

**Comment by yo35** [comment]
Is it OK now? I cannot see any page with a RPB Chessboard game in your website, so it's difficult to see whether it is OK or not on my side.

**Comment by Seb-Fe** [comment]
Yes, it's solved. I suppose was a problem with server cache (although I purged it) or something like this, because I migrate to another server and the problem was gone.
