### ISSUE TITLE
Trying to add the rpb chessboard to my website.

### ISSUE THREAD

**Issue by magius33** [yo35/rpb-chessboard#170]
I have installed and activated the rpb plug in.
I have games I want to show in pgn format. 
How do I upload the games to my wordpress website?

**Comment by yo35** [comment]
Hi,
Sorry for the late reply.
You can upload the PGN files using the "Media" menu in the admin of your website (same as images, PDF files)... You can also inline the content of the PGN files directly in-between the `[pgn][/pgn]` tags.

More explanations regarding the use of the plugin in the admin of your website, menu 'Chess' > 'Memo'.
