### ISSUE TITLE
I lose my PGN files

### ISSUE THREAD

**Issue by JustEggbird** [yo35/rpb-chessboard#172]
I store my PGN files in the /wp-content/plugins/rpb-chessboard folder as suggested. Frequently, one a month or so my PGN files are deleted. Is this associated with an update of the plugin ?

**Comment by yo35** [comment]
Hi,

Sorry for the late reply.

You are not supposed to store any file `/wp-content/plugins/rpb-chessboard` (or any other plugin directory). Indeed, when the plugin gets updated, this directory is removed and replaced by the new version (this mechanism is not specific to RPB Chessboard, all WordPress plugin updates work the same way).

You should use instead the "media" updload tool to upload and save your PGN files. This tool stores the uploaded files in `/wp-content/uploads`.

**Comment by yo35** [comment]
Hi,
Is it OK now?

**Comment by JustEggbird** [comment]
It’s ok

I store little on wordpress, and use the lichess plugin to show  chapters from a lichess study.

Kind regards

Van: Yoann Le Montagner <notifications@github.com>
Verzonden: zaterdag 19 september 2020 14:37
Aan: yo35/rpb-chessboard <rpb-chessboard@noreply.github.com>
CC: JustEggbird <egbert.hulsman@live.nl>; Author <author@noreply.github.com>
Onderwerp: Re: [yo35/rpb-chessboard] I lose my PGN files (#172)


Hi,
Is it OK now?
