### ISSUE TITLE
Is integration with lichess.org/study possible  ?

### ISSUE THREAD

**Issue by JustEggbird** [yo35/rpb-chessboard#173]
Lichess.org delivers a very nice plugin, to insert your Lichess study in a HTML webpage. The plugin is not so so friendly to insert in a wordpress sidebar..... Is a integration of rpb-chessboard and a Lichess study possible....?

**Comment by yo35** [comment]
RPB Chessboard is meant to display chess games and diagrams on its own. If you want be able to have some Lichess content within a WordPress website, this is a totally different plugin.

**Comment by JustEggbird** [comment]
Thank you,

I think there is no extra plugin needed. Lichess has an API to export games you can import in RPB-Chessboard as PGN file. It would be nice if I could place the API call in RPB-chessboard.

Kind regards,

Egbert Hulsman




Van: Yoann Le Montagner <notifications@github.com>
Verzonden: woensdag 12 augustus 2020 18:51
Aan: yo35/rpb-chessboard <rpb-chessboard@noreply.github.com>
CC: JustEggbird <egbert.hulsman@live.nl>; Author <author@noreply.github.com>
Onderwerp: Re: [yo35/rpb-chessboard] Is integration with lichess.org/study possible ? (#173)


RPB Chessboard is meant to display chess games and diagrams on its own. If you want be able to have some Lichess content within a WordPress website, this is a totally different plugin.
