### ISSUE TITLE
Scroll down all page when click on next move 

### ISSUE THREAD

**Issue by pedrosarkis** [yo35/rpb-chessboard#174]
When I click in any of these buttons, it scrolls down all my page.
![image](https://user-images.githubusercontent.com/22531754/90303597-a0eb1900-de85-11ea-8ac2-8e5af69c8a97.png)

**Comment by pedrosarkis** [comment]
Hey, thanks for the reply, my theme is the "Newspaper", and I tried to disable every plugin,but  the issue still happens :(

**Comment by dredaz** [comment]
I faced the same issue when the post content is called out with Ajax

For example, shortcode will work great on 1st post. But if I used some kind of infinitive scroll plugin to load the 2nd post after the 1st post ended, clicking on the move on 2nd post will lead to page jump.

**Comment by yo35** [comment]
@dredaz Your issue has nothing to do with the problem described in this thread. Hopefully, it is probably easy to fix: in the admin of your website, menu "Chess" > "Setting" > "Compatibility settings", disable "Lazy-loading for CSS/JavaScript files".

**Comment by yo35** [comment]
@pedrosarkis There is no theme named "Newspaper" on WP.org. There are "Newspaper lite", "TA Newspaper", "Newspaperist", and a dozen of other themes whose name is based on "newspaper", but none of them is exactly "Newspaper".

**Comment by yo35** [comment]
No update on this issue for more than 3 years, closing...
