### ISSUE TITLE
diacritics

### ISSUE THREAD

**Issue by Ydernek** [yo35/rpb-chessboard#175]
Hi, I have an diacritic problem, it doesn't display properly if I upload a PGN file.

**Comment by yo35** [comment]
Hi,
Sorry for the late reply.
Diacritics are supposed to be properly handled by RPB Chessboard, as long as the PGN file uses the same charset as the one used by your theme (UTF-8 most likely).
You can use the text editor Notepad++ (https://notepad-plus-plus.org/) for charset conversion (see menu "Encoding"). Other converters are also available on the net (google "charset converter" for instance).

**Comment by yo35** [comment]
No news about that, thus I guess it's OK now => closing the issue.
