### ISSUE TITLE
Police des coups et commentaires

### ISSUE THREAD

**Issue by oursemare** [yo35/rpb-chessboard#177]
Bonjour,
Les coups et commentaires sous l'échiquier apparaissent en caractères trop petits, cela nuit à une bonne lisibilité de la page.
Serait-il possible d'avoir une option pour choisir la taille de la police ?
Cordialement
GM

**Comment by yo35** [comment]
Bonjour,
Ceci a déjà été discuté dans le fil suivant : #165 

Je ne compte pas ajouter d'option pour personnaliser les polices de caractères, pour les raisons décrites dans #165. J'ajoute qu'il existe un contournement simple pour réaliser ceci, en utilisant des instructions CSS personnalisées. Par exemple:

```
.rpbchessboard-chessgame {
	font-size: 200%;
}
```
... permet d'agrandir la taille des polices dans les parties insérées avec `[pgn][/pgn]`.

WordPress offre la possibilité d'ajouter de façon simple ce type d'instruction CSS personnalisés via l'admin > menu 'Appearance' > 'Customize' > 'Additional CSS'. Et plein de documentation est disponible sur le net sur le langage CSS si vous souhaitez aller plus loin dans la personnalisation des polices de caractères.

**Comment by oursemare** [comment]
Bonjour,

Merci pour toutes ces informations.
Je vais essayer de m'en sortir avec cela.
J'aurai dû faire un IUT informatique, comme c'était prévu après mon BAC,
plutôt que champion de France ;)

Cordialement
Gilles Miralles

<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Garanti
sans virus. www.avg.com
<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>
