### ISSUE TITLE
Jumpy when you first click on the moves.

### ISSUE THREAD

**Issue by leonfresh** [yo35/rpb-chessboard#179]
Hi very good plugin one small thing:

https://streamable.com/ffagvj

When I first click on the moves my screen jumps. Any fix for this?

Also what is the right code to use if I want to display the navigation board like in the demo?

Thanks.

**Comment by leonfresh** [comment]
The site is chesstuts.com I'm using Pluto theme

**Comment by yo35** [comment]
Hi,
I don't see any issue on the video, and the behavior looks OK to me when I visit chesstuts.com. At which time point in the video is the problem? Can you describe precisely the mouse actions at this point, and the browser you are using? And by the way, on which page of chesstuts.com can I reproduce the problem?

Regarding the configuration of the navigation board, extensive help is provided in the admin > menu 'Chess' > 'Help'.

**Comment by leonfresh** [comment]
Hi thanks for the reply. I changed my theme and it's fine now. I think it clashes with infinite scroll most likely. I don't see the help for navigation board, can you please provide a screenshot? thx

**Comment by yo35** [comment]
![help](https://user-images.githubusercontent.com/5740068/94950177-795a1980-04e2-11eb-80a3-61c084779729.png)
