### ISSUE TITLE
Board Empty

### ISSUE THREAD

**Issue by ddyok** [yo35/rpb-chessboard#180]
I'm trying to get rpb chessboard working on Wordpress, but the board appears empty (no pieces, empty labels on buttons and so on). I suspect that it's because of css being overridden (is there a way to have rpb override what's inherited from the css?), or perhaps this is some incompatiblity with the theme? I don't see any errors, and I'm having a difficult time debugging this. [A test page with how it looks with this link](https://thedecadentreview.com/corpus/test-chess-2/). Any help appreciated.

<img width="1069" alt="Screen Shot 2020-10-02 at 11 13 28" src="https://user-images.githubusercontent.com/16831511/94907785-31120b80-0490-11eb-9db1-f0f65e578a7b.png">

**Comment by yo35** [comment]
Hi,
In the header of your page, there is the following CSS stylesheet that is injected:
```
<link media="all" href="https://thedecadentreview.com/wp-content/cache/autoptimize/css/autoptimize_028eec529311a8b11cedb0c45af14d35.css" rel="stylesheet">
```
And in this CSS, there is the following instructions that override all the settings done by the plugin:
```
.single-post * {
    background: #f4f4f4 !important;
}
body * {
    color: #424242 !important;
}
```
I don't know where this `autoptimize_xxx.css` comes from (most probably from the theme, but I cannot check on my side), but there is nothing the plugin can do against those `!important` tags. I suggest you contact the editor of the theme to have this fixed.

By the way, when you enable the developper tools (press F12 key in Chrome or Firefox) and you manually disable those two instructions, the chessboard looks OK:
![chessboard](https://user-images.githubusercontent.com/5740068/94909630-c10d8080-04a3-11eb-8089-30e0866bd633.png)

**Comment by ddyok** [comment]
Thank you. Removed the .single-post * color (now no !important) and that solved it!
