### ISSUE TITLE
Displaying mid-game moves with [FEN] tag in PGN/[SetUp "1"] 

### ISSUE THREAD

**Issue by ddyok** [yo35/rpb-chessboard#181]
I'm attemping to use the Fen tag/SetUp in order to show mid-game moves (discarding some). I'm not sure whether this is supported, or whether I'm applying it correctly. I have:

```
[pgn]
[Event ""]
[EventDate "1933.06.12"]
[Result "0-1"]
[White "Marcel Duchamp"]
[Black "Arthur William Dake"]
[FEN "r2q1rk1/pbpn2pp/1p1pp3/5p2/1PPPn3/2BBPN2/P1Q2PPP/3R1RK1 b - - 0 12"]
[SetUp "1"]

1.b4 Nxc3 2.Qxc3 Bxf3 3.gxf3 Qh4 4. Kg2 Rf6  *

[/pgn]
```

But I get:

```
Error while analysing a PGN string.
Invalid move (b4). Invalid non-capturing pawn move.
Occurred at position 195:
...Up "1"]   1.b4 Nxc3 2.Qxc3 Bxf3 3.gxf3 Qh4 4. Kg2 R...
             ^
```

Any comments much appreciated.

Thank you,

D.

**Comment by yo35** [comment]
Hi,
The FEN tag above corresponds to the following position:
![position](https://user-images.githubusercontent.com/5740068/94949492-495e4680-04e1-11eb-9116-3ef069c9c67b.png)

... and obviously `b4` is not a valid move in this position. You probably want to start the main varation as follows:

```
1...Nxc3 2.Qxc3 Bxf3 3.gxf3 etc...
```

**Comment by yo35** [comment]
No news, I guess this is OK now.
