### ISSUE TITLE
Chess Plugin 

### ISSUE THREAD

**Issue by MariumWAlvi** [yo35/rpb-chessboard#184]
Can I use this plugin "RPB Chessboard" in my WordPress website? what would it actually do?

**Comment by yo35** [comment]
Hi,
Yes you can use it. As explained in the plugin description, RPB Chessboard allows you to typeset and display chess games and diagrams in the posts and pages of your WordPress blog, using the standard FEN and PGN notations. I suggest you try it by yourself if you want to make your own idea of what it is possible to do with the plugin.
