### ISSUE TITLE
Text not showing

### ISSUE THREAD

**Issue by chessandmind** [yo35/rpb-chessboard#186]
Hi. The plug is was working fine for a while, but suddenly the text is gone and I can only see the board. I recently changed to the twenty fourteen theme: can that be the reason or is there something else going on?

![image](https://user-images.githubusercontent.com/73586670/97423374-697dfb80-190f-11eb-8f2c-4c3c59b76ad7.png)

**Comment by yo35** [comment]
Hi,
What is the address of your website?

**Comment by yo35** [comment]
No answer for more than a year => closing the issue.
