### ISSUE TITLE
Knight moves in L-shape

### ISSUE THREAD

**Issue by sitatis** [yo35/rpb-chessboard#189]
Hi Yoann,

  I see knight moves like other pieces in the game in a straight line. Is it possible to move in L-shape? Thanks in advance

BR

**Comment by yo35** [comment]
Hi,
It would make arrow rendering more complex, and to be honest, I'm not sure it would improve readability of chess diagrams. And also, it raises some questions: which L-shape should be drawn (there are two possible L-shape for a given knight move) ? And what about non-vertical non-horizontal annotation arrows, should they be rendered as L-shape as well ?
I think the ratio between additional complexity and added value is not worth it. Thus I won't do this feature. Sorry.
