### ISSUE TITLE
arrow colors in settings

### ISSUE THREAD

**Issue by litpiotr** [yo35/rpb-chessboard#190]
the colors of the arrows are very bright (poor), can we be able to change these colors to our own as an option?

**Comment by yo35** [comment]
Done in the last version (5.9.0). Arrow and square marker color is now part of the color theme, as the square colors.
I've also slighlty changed the default color of arrow and square markers in some bundled color themes.

**Comment by litpiotr** [comment]
ok i have upgraded but i don't see the option to change the color of the arrows, what do i need to do?

**Comment by yo35** [comment]
In menu 'Chess' > 'Theming', you can create your own colorsets, and customize the color and marker colors.
