### ISSUE TITLE
Installed, activated, and not working at all

### ISSUE THREAD

**Issue by johnyetter** [yo35/rpb-chessboard#198]
This plugin looks like exactly the tool I am looking for. Unfortunately, after installing, activating, and placing pgn tags in a post, nothing shows up except the tags themselves. Furthermore, I do not see the icon for the graphical user interface for building a board position.

I tried changing Wordpress themes, because I thought the theme might be interfering with the plugin in some manner. That did not help.

I hope that someone has some thoughts, because I was really hoping to use this to start blogging about my chess games.

Thank You,
John

**Comment by yo35** [comment]
Hi,
What is the address to your website? Can you provide a screenshot of what you've entered in the post editor?

Regarding the board position GUI, it is not available anymore since WP switch to Gutenberg. I'm currently working on replugging it. See also #139 on this issue.

**Comment by yo35** [comment]
Hi,
The chess position editor is back, as part of the release 6.0.0 of RPB Chessboard.
No news regarding the rest of the problems described here, I guess they have been solved somehow => I close the issue.
