### ISSUE TITLE
Specify theme on shortcode?

### ISSUE THREAD

**Issue by C4nt3r** [yo35/rpb-chessboard#199]
Hi,

I'm working on a site, and I like this format to be shown on news.
![imagen](https://user-images.githubusercontent.com/54954705/112974378-ad8d5a80-9152-11eb-9055-a0c296c79a9c.png)

Because I allow shortcodes in comments, this format is not ok for comments....
![imagen](https://user-images.githubusercontent.com/54954705/112974536-dd3c6280-9152-11eb-858d-13c5d7314a69.png)

...would like to use popup board for comments. What could be great it's to have a second shortcode to use a specific setup just for comments. I appreciate help to do this.

**Comment by yo35** [comment]
Hi,
Sorry for the late reply.
I'm quite surprised that `[pgn][/pgn]` actually works in comments. Anyway, in this case, you can override the default settings to get the popup board as follows:
```
[pgn navigation_board=frame]
...
[/pgn]
```

**Comment by yo35** [comment]
Old issue => closing.
