### ISSUE TITLE
Problem with WP 5.7?

### ISSUE THREAD

**Issue by geroronimo** [yo35/rpb-chessboard#200]
I upgraded my Wordpress site from 5.6 to 5.7, and I get no chessboards anymore in my posts. Is there any known compability problems with RPB-chessboard and WP 5.7? (Should I roll back to 5.6, or look for other solutions)?

**Comment by yo35** [comment]
Hi,
RPB Chessboard is tested with WP 5.7, and there is no known issue. What is the address of your website?

**Comment by geroronimo** [comment]
Hi,
Thanks for your quick reply.

The site is http://tromsosjakk.no
This post was made a few days ago and included quite a few games:
http://tromsosjakk.no/gjensyn-med-sjakkspalta/gjensyn-med-sjakkspalta-bondesluttspill/

**Comment by yo35** [comment]
Hi,
There is a problem with your theme ("magazine premium"), that fails to load one of its JavaScript library ("Bootstrap"). This error prevents the rest of the Javascript components -- including RPB Chessboard -- from being loaded correctly.

See the errors in the Javascript console (press key F12 to access to that in Chrome or Firefox):
![console](https://user-images.githubusercontent.com/5740068/114014793-4ade4200-9869-11eb-88bb-aa33a8df4629.png)

**Comment by yo35** [comment]
No news for more than a year. I hope things are OK now.

-> Closing the issue.
