### ISSUE TITLE
Highlights and arrows?

### ISSUE THREAD

**Issue by weaksquare** [yo35/rpb-chessboard#201]
Hi, I have looked everywhere but cannot seem to find basic instructions on how to add highlights arrows to FEN positions! Please forgive me if you have instructions on this but I cannot seem to find them. Thanks!

**Comment by yo35** [comment]
Hi,
Here is an example: `[fen csl=Ye5 cal=Gc6e5,Rf3e5] ... [/fen]`
-> this adds a yellow square marker in e5 (`Ye5`), a green arrow from c6 to e5 (`Gc6e5`), and a red arrow from f3 to e5 (`Rf3e5`).

The only available colors are green, red, and yellow, encoded respectively with capital characters `G`, `R` and `Y`. The square markers are described by attribute `csl=...`, the arrows by `cal=...`.

More details about this syntax in the admin, menu 'Chess' > 'Help' > 'PGN game syntax' > 'Square, arrow, and text markers'
