### ISSUE TITLE
Allow to initialize the navigation board at a given move

### ISSUE THREAD

**Issue by armandn** [yo35/rpb-chessboard#205]
Two things that would be helpful:
1. Allow to include the full game but start at a given move. If you always show the navigation board, sometimes you want to skip the opening and start at move 10 for example.
2. Maybe a more forgiving PGN parsing? For example, PGNs that don't end with the result (1-0, etc.) are considered invalid, which is technically true, but it doesn't actually impact anything.

**Comment by yo35** [comment]
OK for the 1st feature (initialize the navigation board at a given move).

My opinion regarding the second feature is that it may be dangerous to consider a PGN string that has not been validated and sanitized. And the more you tolerate "some errors" in what is parsed, the more you are likely to introduce inconsistencies or unpredictable behavior. More specifically, the end-of-game tag (`1-0`, `0-1`, `1/2-1/2` or `*`) is particularly important in the current implementation of the parser, as it is considered as a separator between games in PGN string that contains several of them. Therefore, that's a no for the second feature.

**Comment by armandn** [comment]
Great on the first. Understand on the second. It makes sense, I didn't know multiple PGN games are supported.

**Comment by yo35** [comment]
Customization of the move initially displayed in the navigation board is available in RPB Chessboard version 7.1.0 (just released):

![initial-selection](https://user-images.githubusercontent.com/5740068/170126989-69b80851-d043-4f8b-ab7f-c07ebf1fe795.png)

These controls are available in the right-side panel of the chess game block. They are available only if the navigation board is enabled and NOT configured to be displayed in the popup (which is the default set-up), as customization of the initial move would not make sense in this case (the popup is hidden by default).
