### ISSUE TITLE
Problem after upgrading to WP 5.7

### ISSUE THREAD

**Issue by ddyok** [yo35/rpb-chessboard#207]
RPB Chessboard doesn't seem to load after upgrading to WP 5.7. I'm trying to nail down the issue, or if it's a theme/plugin issue. For example, see the errors at: http://174.138.54.22/corpus/marcel-duchamp-mugged-by-a-street-hustler/

Any ideas welcome.

Thanks a lot,

D.
__

**Comment by ddyok** [comment]
I may have been too hasty in opening the issue. It appears to be coming from autoptimize deferring js code in the new version, which also affects rpb chessboard, not sure it's related to rpb.

**Comment by yo35** [comment]
Hi,
Have you solved your problem? I don't see any error in the above-mentioned page, and the RPB Chessboard components look OK.

**Comment by ddyok** [comment]
I've disabled autooptimze all together for the time being. I don't think that this is an RPB issue, maybe in the way the page loads with scripts deferred... Closing issue, if I'll come up with something specific I'll update. Thank you!
