### ISSUE TITLE
Problem with the sizing of the popup frame of the navigation board on mobile devices

### ISSUE THREAD

**Issue by UnoScacchista** [yo35/rpb-chessboard#208]
Since a few days (apparently further to the 6.0.0 and 6.0.1 updates), the popup frame of the navigation board are badly displayed on mobile devices. The popup frame does not fit the screen and part of it is not visible (regardless of the device and the browser).
![L’Angolo del Finale27 – Uno Scacchista](https://user-images.githubusercontent.com/76403906/120893284-c9115780-c612-11eb-90ab-80843d13a734.png)

Thank you for checking.

Uberto Delprato

**Comment by yo35** [comment]
Thanks for reporting.
This is fixed in version 6.0.2 (just released).

**Comment by UnoScacchista** [comment]
Gr8, thx
