### ISSUE TITLE
Can't see Gutenberg integration

### ISSUE THREAD

**Issue by armandn** [yo35/rpb-chessboard#209]
I feel very stupid for asking, but I don't see any Gutenberg block inserting/editing FENs....  Using WP 5.7.2 and RPB Chess board 6.0.2. What am I missing?

**Comment by yo35** [comment]
The block appears in the "media" section of the block list:

![chess_diagram_block](https://user-images.githubusercontent.com/5740068/121073223-8b5b2d00-c7d2-11eb-927d-f45518bdae68.png)

**Comment by yo35** [comment]
As of RPB Chessboard 7.0.0, there is also a _Chess game_ block... and a proper quick start tutorial explaining how to use the plugin (https://rpb-chessboard.yo35.org/). The plugin should now be more ergonomic than it used to be.
