### ISSUE TITLE
Define diagram via FEN-String

### ISSUE THREAD

**Issue by WalterSchmidt77** [yo35/rpb-chessboard#211]
It would be very nice, when the fantastic Gutenberg-rpb-chessboard-plugin could allow to edit a simple diagram by pasting a FEN-String somewhere - instead of inserting all the pieces. 

Right now, one can do this via Code-Editor, but even there, one has to paste the same FEN-String in two positions.

**Comment by yo35** [comment]
Hi,
This is available in version 6.1.0 (just released). The diagram editor has now a textfield with the FEN string of the edited position. Copy/paste can be performed in that textfield.

Thanks for the feature suggestion.
