### ISSUE TITLE
Feature Request: Not only full games but a part of the game replayable over the board

### ISSUE THREAD

**Issue by schttrj** [yo35/rpb-chessboard#212]
Currently, we have to enter the PGN and full games are replayable. But what if we want to show only a part of the game? Is there a way to do that? If not, can you please include it into the plugin?

**Comment by yo35** [comment]
Hi,
It's possible to squeeze the beginning of a game, and to have it start at a custom position. An example can be found in the admin, menu 'Chess' > 'Help' > 'PGN syntax' > Custom starting position.

**Comment by yo35** [comment]
The documentation relative to this feature is now available at https://rpb-chessboard.yo35.org/documentation/pgn-syntax/#custom-initial-position
