### ISSUE TITLE
Where do I upload the chess pgn?

### ISSUE THREAD

**Issue by ChessLovers** [yo35/rpb-chessboard#214]
Hi.

[pgn url="https://examples.com/wp-content/plugins/rpb-chessboard/examples.pgn" game=0]

Where to upload the pgn? I have downloaded the pgn from chessgames.com but where am I supposed to upload the pgn to? If it is the server, how do I get or find the server?

Thank you.

**Comment by yo35** [comment]
Hi,
You can upload it in the "Media" section of your website.

**Comment by ChessLovers** [comment]
Got it! Thank you so much!
