### ISSUE TITLE
Change the color of the arrow

### ISSUE THREAD

**Issue by headx86** [yo35/rpb-chessboard#216]
I lose focus because the color of the arrow that highlights the last move is blue, it's too dark. I want to change it to light color for example gray.
please keep the blue color to mark the squares like lichesss, chessbase, chesscom
Help me please!

**Comment by yo35** [comment]
Hi,
You can change the default colors by creating a new colorset: in the admin, menu 'Chess' > 'Theming' > 'Colorset' > 'Add a new colorset'.

![add_colorset](https://user-images.githubusercontent.com/5740068/135977155-8e75ea93-33d9-430b-b60a-2770755d1273.png)

Once the colorset is created, set it as the default one with 'set default'.

**Comment by headx86** [comment]
Thank you very much :D
