### ISSUE TITLE
Navigation board

### ISSUE THREAD

**Issue by tcnesham** [yo35/rpb-chessboard#217]
What are the tags used to create a Navigation board as seen here: https://rpb-chessboard.yo35.org/navigation-board/ ?

I have seen [pgn][/pgn] which works nice, but I'd prefer not having a board pop-up as seen in that link.
I assume I start off with a shortcode block as well?

Thanks for the help.

**Comment by tcnesham** [comment]
Ok, I found it.
Example,
[pgn navigation_board=floatLeft]

**Comment by yo35** [comment]
Hi,
Just to mention (althought you may have already find it): the documentation for the tags associated to `[pgn][/pgn]` is available in the admin, menu 'Chess' > 'Help' > 'PGN tag attributes'.
