### ISSUE TITLE
Is it possible to change the font face of the chess moves in text ?  

### ISSUE THREAD

**Issue by JustEggbird** [yo35/rpb-chessboard#219]
Do I have to edit the css.....?

**Comment by yo35** [comment]
Hi,
The plugin uses the font defined by the WordPress theme. No option is provided by the plugin to change that. If you still want to use a different font for the chess moves than for the rest of your articles/pages, you must edit the CSS.

**Comment by JustEggbird** [comment]
with different theme's , a bad view is :  [https://chaturanga.nl/index.php/2023/04/18/top-partij-tobias-arnoldussen/](url) , a good view : [http://nieuws.hetgambiet.nl/2023/04/almere-egbert-hulsman-tycho-rietveld](url)

**Comment by JustEggbird** [comment]
which css is needed ?

PS.
bad : [https://chaturanga.nl/index.php/2023/04/18/top-partij-tobias-arnoldussen/](https://chaturanga.nl/index.php/2023/04/18/top-partij-tobias-arnoldussen/)
good: [http://nieuws.hetgambiet.nl/2023/04/almere-egbert-hulsman-tycho-rietveld](http://nieuws.hetgambiet.nl/2023/04/almere-egbert-hulsman-tycho-rietveld)

**Comment by JustEggbird** [comment]
I need some lines of extra css in the Hichtcock theme. The text view is very condensed,  a like a normal view like in the Twenty Twenty theme ...

**Comment by yo35** [comment]
You may use for instance:

```
.rpbchessboard-chessgame {
  line-height: 150%;
}
```

But I suggest you ask to the theme author if there is something wrong with the theme (typically if the line height defined in the Hichtcock theme is too small).

And if you want to do some advance CSS tweaking, I suggest you refer to the general purpose documentation available on the web to know how to do so.

**Comment by JustEggbird** [comment]
Thank you, much better ...
