### ISSUE TITLE
How to  display initial position of a pgn file

### ISSUE THREAD

**Issue by stevex24** [yo35/rpb-chessboard#225]
The initial position only displays after clicking the first move of the solution. Is there a way to show this as part of the puzzle before clicking on a move
<img width="1159" alt="dhess puzzle" src="https://user-images.githubusercontent.com/3274178/150625562-87efc76b-13b1-4ab1-bb35-c70be8955b00.png">
?
Here the position is a separate fen string
The text is what the user sees before clicking on the first move of the solution

No - never mind - I found examples of {[pgndiagram]} online after I couldn't find a usage manual.

**Comment by yo35** [comment]
Hi,
Indeed, `{[pgndiagram]}` (or equivalently `{[#]}`) does the job.
The usage manual is in the admin part of your website, menu 'Chess > Help'.
