### ISSUE TITLE
Could you start viewing the pgn file from the last playthrough?

### ISSUE THREAD

**Issue by chipyte** [yo35/rpb-chessboard#228]
Could you start viewing the pgn file loaded by url, starting with the last move of the file? That is, the first thing that is shown is the last move of the pgn. I want to update the pgn loaded by url, and I need it to show as the first move on the board, the last move of the pgn, could that be possible? . One other thing, to avoid errors I also need to remove the need to put 1-1 or 0-1 or 1-0 at the end of the png, in that pgn file just open one game. So I don't need you to identify that, Thank you, Kind regards....

**Comment by yo35** [comment]
Hi,
Currently, it's not possible to change the move displayed by default, but this feature has already been requested (see #205), thus I will probably implement it at some point.
Regarding the need of having a game termination marker (`1-0`, `1/2-1/2`, etc.) at the end of the file: this is required by the PGN format. Still, for open games, you can use `*`.

**Comment by yo35** [comment]
Done in RPB Chessboard version 7.1.0 (just released). See #205 for more details.
