### ISSUE TITLE
How to divert ?

### ISSUE THREAD

**Issue by JustEggbird** [yo35/rpb-chessboard#235]
When you need a diagram with diagram alignment "right" and another diagram with diagram alignment "none" ? Is that possible ?

**Comment by yo35** [comment]
Diagram settings can be overridden in the "Chessboard aspect" tab on the right-hand side of the page/post editor:

![diagram_aspect](https://user-images.githubusercontent.com/5740068/166103936-1bbfd834-d173-4de2-9996-2fc71e99fbac.png)

This allows to have distinct diagram alignments from one diagram to another.

**Comment by JustEggbird** [comment]
Sorry,

Problem solved.


Kind regards,
Egbert

Van: Egbert Hulsman
Verzonden: zaterdag 30 april 2022 14:32
Aan: yo35/rpb-chessboard ***@***.***>; yo35/rpb-chessboard ***@***.***>
CC: Author ***@***.***>
Onderwerp: RE: [yo35/rpb-chessboard] How to divert ? (Issue #235)

Nice,

But I miss the right side options ?
Where do I go wrong ?

Kind regards,
Egbert Hulsman


Van: Yoann Le Montagner ***@***.******@***.***>>
Verzonden: zaterdag 30 april 2022 13:39
Aan: yo35/rpb-chessboard ***@***.******@***.***>>
CC: JustEggbird ***@***.******@***.***>>; Author ***@***.******@***.***>>
Onderwerp: Re: [yo35/rpb-chessboard] How to divert ? (Issue #235)


Diagram settings can be overridden in the "Chessboard aspect" tab on the right-hand side of the page/post editor:

[diagram_aspect]<https://user-images.githubusercontent.com/5740068/166103936-1bbfd834-d173-4de2-9996-2fc71e99fbac.png>

This allows to have distinct diagram alignments from one diagram to another.

**Comment by JustEggbird** [comment]
Nice,

But I miss the right side options ?
Where do I go wrong ?

Kind regards,
Egbert Hulsman


Van: Yoann Le Montagner ***@***.***>
Verzonden: zaterdag 30 april 2022 13:39
Aan: yo35/rpb-chessboard ***@***.***>
CC: JustEggbird ***@***.***>; Author ***@***.***>
Onderwerp: Re: [yo35/rpb-chessboard] How to divert ? (Issue #235)


Diagram settings can be overridden in the "Chessboard aspect" tab on the right-hand side of the page/post editor:

[diagram_aspect]<https://user-images.githubusercontent.com/5740068/166103936-1bbfd834-d173-4de2-9996-2fc71e99fbac.png>

This allows to have distinct diagram alignments from one diagram to another.
