### ISSUE TITLE
bbPress Integration?

### ISSUE THREAD

**Issue by infinitless** [yo35/rpb-chessboard#236]
Can users embed Chessboards in bbPress forum posts?

**Comment by yo35** [comment]
See discussion in #65 

To cut a long story short: it's not possible by default. But it should be possible by installing another plugin (https://wordpress.org/plugins/bbpress-do-short-codes/), + disabling "Lazy-loading for CSS/JavaScript files" in the RPB Chessboard options, to insert a diagram with `[fen]<FEN representation of the position>[/fen]`. I've never tried this process by myself.

**Comment by infinitless** [comment]
It works with the recommended method above! Thanks!
