### ISSUE TITLE
Sie müssen JavaScript aktivieren, um die Diagramme zu verbessern.	

### ISSUE THREAD

**Issue by estruth** [yo35/rpb-chessboard#237]
you have to activate javascript to improve the diagrams. Fact is I see no diagram. I have a custom template "www.Schachklub-wiehe.de" and in a earlier version of the plugin there was that problem missing javascript too.
thanks in regard

**Comment by yo35** [comment]
I cannot reach your website at http://www.schachklub-wiehe.de

I cannot analyze the issue if the website is not reachable.

**Comment by yo35** [comment]
No update for more than 1 year and half, closing the issue...
