### ISSUE TITLE
<br> tags embedded within PGN comments stopped working

### ISSUE THREAD

**Issue by friscodelrosario** [yo35/rpb-chessboard#238]
I used to embed a br tag within a PGN comment, and the result looked like this:
![screen2](https://user-images.githubusercontent.com/59985/170849193-a793f94d-c3ec-4c5f-947f-5efe28f9c96a.jpg)

Today the same tag results in:
![screen](https://user-images.githubusercontent.com/59985/170849208-431a47e0-fd18-4bb7-b6a6-2ec53886fc52.jpg)

**Comment by yo35** [comment]
What is the address of your website?

**Comment by friscodelrosario** [comment]
http://friscodelrosario.net/

> What is the address of your website?
