### ISSUE TITLE
bug: rpb crashes the server if comment is quite big

### ISSUE THREAD

**Issue by buffos** [yo35/rpb-chessboard#24]
If the comment inside the { } is quite big (2-3 lines will do), rpb crashes the server

**Comment by richiwalt** [comment]
Fwiw ... Just reading this thread, I tried the example also.   The Wordpress article rendered fine in the browser. Makes me curious about the problem that you're experiencing buffos.

**Comment by yo35** [comment]
Closing the ticket as the bug does not seem to be reproducible and no one has reported a similar problem for nearly 3 years.
