### ISSUE TITLE
Limit to size of PGN file?

### ISSUE THREAD

**Issue by friscodelrosario** [yo35/rpb-chessboard#241]
I annotated a game of 75 moves and 2300 word count. I wouldn't have expected either of those to break rpb-chessboard, but my WP preview shows nothing from the draft (not even a malformed PGN warning).

**Comment by friscodelrosario** [comment]
I reduced a WP document to nothing but the large PGN, and got the same unwanted result.

**Comment by yo35** [comment]
Can you provide a link to the page on which you encounter this issue?

**Comment by friscodelrosario** [comment]
> Can you provide a link to the page on which you encounter this issue?

http://friscodelrosario.net/?p=1417&preview=true

**Comment by friscodelrosario** [comment]
> Can you publish this page? Otherwise I cannot access it.

http://friscodelrosario.net/2022/06/22/test/

**Comment by yo35** [comment]
And can you join the PGN as well?

**Comment by friscodelrosario** [comment]
> And can you join the PGN as well?

[Event "CalChess Senior"]
[Site "Berkeley"]
[Date "2022.06.19"]
[Round "5"]
[White "Kenny"]
[Black "Del Rosario"]
[Result "0-1"]
[ECO "A40"]

1. d4 b5 {Spassky played this a few times, for a different reason.} 2. Bf4 {
Club players typically fall into categories of "fashion-conscious" and/or
"lazy". When the top players adopt an opening, the bottom players are certain
to follow. Among today's elite, Carlsen, Praggnanandhaa, and Giri have played
the London. In the 1920s, Capablanca, Nimzovich, and Rubinstein. The question I
have for the fashionistas is "what do you think of the 'Baltic Defense' to the
Queen's Gambit as Black, and the Colle System as White?". The defense 1. d4 d5
2. c4 Bf5 was never fashionable M the only names who played it frequently that
one might recognize are Malaniuk and Opocensky (in my neck of the woods,
Mezentsev). 2...Bf5 is just as playable as the other piece moves 2...Nc6 and
2...Nf6, but elite players don't trust Black's shaky queenside (3. Qb3 is an
immediate possibility), and that the bishop is vulnerable (but this doesn't
bother Slav defenders, whose f5-bishops are pushed about), and that it's a
rather premature development M you don't know yet where you want that bishop.
The Colle System 1. d4 2. Nf3 3. e3 4. Bd3 was never fashionable with the
modern elite, because it's not sharp enough and doesn't lend itself to
long-term pressure. For the modern players, it's said to be for those who
"prefer to save the fight for the middlegame"; only Yusupov played it
regularly. Because it's not popular with modern elite, it's not popular with
modern duffers, who don't recognize the Colle System as a fearsome attacking
weapon (which it is, truly; see a sample of Edgaard Colle's games). The only
difference between the London, which is all the rage, and the Colle, which
never caught on, is that in the Colle, the c1-bishop is patient, waiting to be
sprung after e3-e4. That's the sole difference, and it's actually a bonus for
club players, who benefit from the landscape suggesting the best placement for
the bishop. Top players can mold the game to suit their early Bf4 development,
bottom players should enable the position to guide them. Along with
fashion-conscious, chessplayers are also lazy. Chess opening that are called
'systems' (London, Colle, Barcza, Gurgenidze, usw) don't care what the opponent
is doing (in this game, for instance; my opponent looked at the odd 1...b5 for
a second, then went ahead with his London formation). A system player can put
the pawns and pieces in the system setup under almost any condition. So it
isn't necessary to learn book lines (though chessplayers are dumb, and heavily
invest in London System books), and lazy chess teachers can't miss with the
London. I've often said that no chess teacher gets fired for teaching 1. e4 e5
2. Nf3 Nc6, thought that's all wrong for beginners and players who don't think
they're beginners. Likewise, chess teachers will never get fired for 1. d4 2.
Nf3 3. Bf4 4. e3 5. Bd3 6. Nbd2 7. O-O, either. It's efficient and super solid,
so what's not to like? Like I said, it's that f4-bishop. If chess teachers
taught the Colle System as a fearsome weapon, with that c1-bishop sitting
patiently, I'd be all in favor (I teach the Colle myself, if I think the
student is up to it). But chess teachers are usually as fashion-conscious as
the other club players, so they latch on to 2. Bf4 or 3. Bf4 like it's gospel.
Isn't it weird? I recommend 1. d4 2. Nf3 3. e3 4. Bd3 as a weapon, but
recommend against 1. d4 2. Nf3 3. Bf4 4. e3 5. Bd3 as too sophisticated. It's
the truth, though M say a player began with a Colle setup, and later determined
that the c1-bishop belonged on f4, transposing to a position that could just as
easily be reached from the London. I'd have no problem with that at all.       
} 2... Bb7 3. e3 Nf6 4. Nd2 a6 {My game against IM Taylor in round one
convinced me that as White, I should persist with the b-pawn instead of
propping it up. As Black, I don't know.} 5. h3 {London players love this
super-sneaky little pawn move to provide luft for the bishop. I think that's
part of the appeal for club-level London players; they get a reason to play
P-R3, which is a favorite move of weak players when it's just a waste of time.}
5... d6 6. Ngf3 Nbd7 7. c3 g6 8. Bh2 { Sometimes they wait for ...Nh5 to pull
back, but in this case, Black can see ...e7-e5 coming.} 8... Bg7 9. Be2 e5 10.
O-O ( {LC Zero and Stockfish both say} 10. dxe5 {, so if ...d6xe5 plus
...e5-e4, then White can advance Nf3-e5.} ) 10... e4 {White didn't mind,
because he saw Nf3-e1-c2-b4 as useful.} 11. Ne1 O-O 12. a4 Bc6 13. axb5 axb5
14. Nc2 Nb6 15. Nb4 Bd7 16. Qc2 c5 {Stockfish thinks this is bad, that Black
should just develop with 16...Re8 or 16...Qe7 (imagine that). Black opened the
position while trailing in development, then had to squirm.} 17. dxc5 dxc5 18.
Na6 {Black has two pawns hanging: e4 and c5.} 18... Qe7 19. Nc7 {Black is
forked at a8 and b5, and has to give up the a-file if he wants to save the
pawn. I saw this at move 18, and instead of passive defense, I spent 30+
minutes looking to sacrifice rook for knight if that meant active pieces,
instead of losing a pawn for nothing or giving White all the piece activity.
Purdy said if you have a choice of losing a clear pawn or an exchange while
preserving activity, lose the rook. I couldn't see a useful exchange sacrifice
at move 18, and decided after the long think to cling to the pawn and figure
out what to do after Ra1-a7 when it arrived. } 19... Rxa1 20. Rxa1 {Stockfish
thinks White is winning, with leads in development and pressure.} 20... b4
{Here it occurred to me that it isn't 21. Ra1-a7 that I should've worried
about; it's 21. Ra1-a6. Then he picked up his rook, and I waited to see where
it would land.} 21. Ra7 { Stockfish evaluates}  (21. cxb4 cxb4 22. Ra6 { as
+3.7, and 21. Ra7 as +1.7, because it doesn't threaten. } ) 21... Nc8
{Stockfish said the undeveloping move can wait, and that a rook development is
in order (imagine that). } 22. Ra6 bxc3 23. bxc3 Rd8 {I felt like I was nearly
out of the woods, but Stockfish says White is still winning if he sets his
sights on the c5-pawn.} 24. Nc4 Ne8 {Another undeveloping move, but the
computer is OK with this one.} 25. Nd5 Qg5 26. Nf4 { }  ( {After } 26. Qxe4 {,
Black might get the pawn back on h3, but it's the best way for White to
preserve the advantage. His center presence is very much the better, making the
blip in the king position inconsequential.} ) 26... Nc7 27. Ra5 ( {Anand once
said about 1. e4 e5 2. Nf3 Nc6 3. Bc4 Bc5 4. c3 Nf6 5. d3 d6 6. O-O a6 that
when the black bishop gets hit, it should fall back to a7 because White is
likelier to lose sight of it there than on b6. I had lost sight on the bishop
on h2 (super sneaky h2-h3! for the win), and White should capitalize by} 27. h4
Qxh4 28. Nxg6 hxg6 29. Bxc7) 27... Nb5 {I felt like I was finally getting
somewhere, but Stockfish says the 0.3 advantage conferred to White with the
first move is still in place.} 28. g3 {That's just strange, but nearing the
third hour, senior players can lose track (I don't know about him, but I'd
chewed more than two-thirds of my clock time, and I was beat). The London
bishop was unleashed after 27. h4!, but is instead buried by 28. g3.} 28...
Nxc3 29. h4 Nxe2+ {My first "easy" move. Stockfish thinks Black is comfortably
ahead and almost winning, but that's the thing about Stockfish: It has the same
energy whether it's the first or last game of the tournament.} 30. Qxe2 Qf5 31.
Qc2 Bc6 32. Nd2 Bf8 33. Ne2 Qd7 34. Nb3 Qd3 {Black is now driving (-6 according
to the computer), but I was running on empty, out of good ideas.} 35. Ra2 {The
only move to save -6 from increasing to -8} 35... Bb5 $2 ( {The simplest way is
to pin with} 35... Ba4 { because the rook is overworked, and} 36. Qxd3 exd3 {
should end things.} ) 36. Nbc1 Qd1+ {-6 is down to -3.7, and I'd spent most of
my remaining clock time on 35...Bb5?. } 37. Qxd1 Rxd1+ 38. Kg2 c4 $2 (38... Bd7
{is a good move if Black wants to form a mating net} )  ( {, } 38... h5 { is a
good move to keep the white bishop under wraps, and} )  (38... Bc4 39. Rc2 Bd3
{ is good to help the c-pawn advance. In danger of losing on time, you lose
the ability to think logically. I remember looking at the pieces on the back
row, and thinking it couldn't be a bad idea to put one back in the game, but I
couldn't attach any of those piece moves to a plan. If this were a student's
game, I'd Black isn't looking to form an endgame plan as much as mobilizing the
opening pieces, and if I were playing this as a blitz game, I imagine I
might've played 38...Nd6 as a rational move if I couldn't think of one of the
good moves forementioned.  } ) 39. Nc3 Rxc1 40. Nxb5 c3 {I look at this two
days later, and think I must've bashed ...c5-c4-c3-c2 because it added some
time to the clock.} 41. g4 c2 {The pawn is dead. Some players who get into time
trouble like it. I think at some point in their chess lives, they sprung some
brilliant and miraculous combination with the flag on the brink, and thought
they got addicted to time pressure because they might get that incredible rush
again. Some players, like the American champions Browne and Reshevsky, believe
they had it all figured out, and could demonstrate so with their flags hanging.
I don't believe that is possible, but Browne and Reshevsky did, and they were
both great players with weird lives, so who knows how their minds operated.
Some players just lack trust in their ability to calculate and evaluate those
calculations, and wind up looking at the same things repeatedly. I'm in that
group. 18...Qe7 burned so much time because I re-examined the exchange
sacrifices, which were not good. I re-examined the moves that just lost a pawn,
which were not good. And each time I re-examined 18...Qe7, I felt dread about
21. Ra7 M which wasn't the move to be afraid of! M before coming to grips with
"well, maybe that is dreadful, but you're going to have to live with it,
because you have to do *something*".   } 42. Kh3 Nd6 43. Nd4 Kg7 {Stockfish
evaluates the position as 0.18, which doesn't mean a lick to club players (the
Internet users M I can't be sure they're actually chessplayers M who argue over
one-tenth of a pawn here or one-tenth of a pawn there are the technological
equivalents of book players who hinge on += or =). There's nothing left to play
for, so I offered a draw with 43...Kg7.} 44. Rxc2 { He refused the draw. He
didn't have anything to fear on the board, and maybe I'd lose on time.} 44...
Rxc2 45. Nxc2 f5 46. g5 Nc4 {One of the paradoxes about chess M one that makes
minor piece endings especially tricky for the player who is considering
simplifying the position M is that the principle "bishops are better than
knights in the endgame" doesn't apply to *two* types of positions. Most players
know the knight is preferable in blocked pawn positions, but fewer players know
that if the pawns are all on the same side, then the knight is preferable for
its ability to use both square colors, while the bishop's longer range is much
less relevant in a game where only half the board matters. Therefore, Black
must move that knight else Bxd6.   } 47. Nd4 Kf7 48. Bb8 Bc5 {The other thing
that perhaps White hadn't accounted for is the principle that bishops are
better placed on the square color opposite the pawns. Sometimes the player
can't help it M maybe a passive defense for the bishop is in order M but this
isn't one of those games. For much of this endgame, Black can see the f2- and
h4-pawns as targets, and even the e3-pawn could be a square on which to
sacrifice a piece.} 49. Ne2 Nd2 50. Ng1 { Nd2-f3 would be troublesome, right?} 
50... Ke6 { The only thing Black has to play for is moving the king around to
attack f2. } 51. Bf4 Kd5 52. Ne2 Kc4 53. Bg3 Nf3 54. Nf4 Bd6 55. Ne6 Bb4 56.
Kg2 Kd3 57. Kf1 Kd2 58. Nc7 Kd1 59. Nd5 Nd2+ 60. Kg1 Bf8 61. Nf6 h6 62. gxh6
{If White wants to give Black a chance to go wrong, it's 62. h5, but White
fell behind on the clock somewhere, not leaving him time to think about the
double-edged move.} 62... Bxh6 63. h5 Bg5 {There's a tactical trick attached to
63. Bg5 that doesn't go with 63. Bg7.} 64. Nh7 Nf3+ 65. Kg2 {He returned the
draw offer, but Black gets a clear advantage.} 65... gxh5 66. Nxg5 { White
must've hated this move, but ...Bg5-e7 to corral the knight was in view. 65.
Nf8 extricates the knight, but it's far out of play.  } 66... Nxg5 67. Bh4 Nf3
68. Bg3 h4 69. Bf4 Ke2 {The h-pawn is the "outside passed pawn" that one
jettisons for profit elsewhere.} 70. Bh6 h3+ 71. Kxh3 Kxf2 72. Bf4 Ng1+ {I was
about to blow this game for the second time. I'd accumulated three minutes on
the clock, plenty of time to take a breath before }  (72... Nd2 {then ...Nf1 or
...Nc4. When the time control increments one's clock, one has to recognize when
the time pressure is off, so slow down and resume thinking.} ) 73. Kh4 Kf3 $4 (
73... Ne2 $19) 74. Kh5 $4 { If White shifts the bishop to the e3-a7 diagonal,
he'll have time to capture the f5-pawn, then throw the bishop on e3.} 74... Nh3
{No one knew it at the time, but this is the only move that preserves the win
after 74. Kh5??.} 75. Bh6 f4 $4 (75... Nf2 76. Kg6 Ng4 77. Bf4 Nxe3 $19 {is the
way. White's overstepped the time limit} ) 76. exf4 e3 (76... Nxf4+ 77. Kh4 e3
78. Bf8 $10) 77. f5 e2 78. Bd2 $10 0-1

**Comment by yo35** [comment]
There is no problem with this PGN in my test environment:

![long-pgn](https://user-images.githubusercontent.com/5740068/175113963-12f74e83-56d7-4796-ad4a-e098ed7dfde8.png)

Thus there should be another plugin (or theme) in yours that leads to this unexpected behavior. I suggest you perform the following tests:
- try with a smaller PGN to see whether the problem is related to the PGN length,
- if you are using the `[pgn]...[/pgn]` shortcode, try the *Chess Game* instead,
- try to de-activate as many plugins as possible and to switch to a standard theme ("twenty-twenty two for instance) to determine what causes the conflict.

**Comment by friscodelrosario** [comment]
> There is no problem with this PGN in my test environment:
> 
> ![long-pgn](https://user-images.githubusercontent.com/5740068/175113963-12f74e83-56d7-4796-ad4a-e098ed7dfde8.png)
> 
> Thus there should be another plugin (or theme) in yours that leads to this unexpected behavior. I suggest you perform the following tests:
> 
>     * try with a smaller PGN to see whether the problem is related to the PGN length,
> 
>     * if you are using the `[pgn]...[/pgn]` shortcode, try the _Chess Game_ instead,
> 
>     * try to de-activate as many plugins as possible and to switch to a standard theme ("twenty-twenty two for instance) to determine what causes the conflict.

I didn't know there was an alternative to the shortcode. Does _Chess Game_ go inside braces?

**Comment by friscodelrosario** [comment]
> https://rpb-chessboard.yo35.org/examples/chess-game/

I see. Perhaps I should use the block editor.

**Comment by yo35** [comment]
No update for 1 year and half, closing the issue...
