### ISSUE TITLE
No render in last versions

### ISSUE THREAD

**Issue by juanparra64** [yo35/rpb-chessboard#242]
Hi.
I have been using RPB Chessboard for some years, but since last updates, all my chessgames are missing in all my webpages. I can see the right rendering in Maxthon 5, but all the games are not diplayed in Chrome, Firefox or Maxthon 6.
In this page I have 3 games: https://www.guapaweb.es/en-memoria-de-un-amigo-jose-carlos-menendez-solar/
This is an image of the first game in Maxthon 5:
![2022-06-29 21_43_19-game1](https://user-images.githubusercontent.com/71660748/176528802-f072fa28-8903-4bf5-afc1-b72400e18d58.png)
The code of this game is:
[pgn_compat navigation_board=left piece_symbols=figurines url="https://www.guapaweb.es/wp-content/uploads/2022/06/202206p19841222carlosparra.pgn" game=0][/pgn_compat]

The other two games are similar:
[pgn_compat navigation_board=left piece_symbols=figurines url="https://www.guapaweb.es/wp-content/uploads/2022/06/202206p20080703arribasmaritzacarlos.pgn" game=0][/pgn_compat]

[pgn_compat navigation_board=frame piece_symbols=figurines url="https://www.guapaweb.es/wp-content/uploads/2022/06/202206p20211127carlosmontousse.pgn" game=0][/pgn_compat]

Thanks in advance.

**Comment by yo35** [comment]
Hi,
It seems you have a cache plugin (LiteSpeed) that performs some risky optimization operations regarding how JavaScript files are loaded, typically using deferred/async loading. You should try to disable that.

**Comment by yo35** [comment]
I've released a new version (7.3.1) that may mitigate this rendering issue in configuration such as yours. Still, given the number of errors and warnings that are raised when I display your frontpage in a browser, there is definitely something wrong with the configuration of your website:

![errors](https://user-images.githubusercontent.com/5740068/176627739-38993e1b-b29d-4f24-bd9c-93f813d04a28.png)

(screenshot taken with Firefox, but the result is more or less the same with Chrome)

**Comment by yo35** [comment]
By the way, when your website is loaded without LiteSpeed cache optimizations (using the `/?LSCWP_CTRL=before_optm` trick, as advised in https://docs.litespeedtech.com/lscache/lscwp/ts-optimize/), the chess games are OK.

I suspect the JS minify feature implemented in LiteSpeed to have some nasty side effects.

**Comment by juanparra64** [comment]
I deactivated the option and it is running ok again!
![2022-06-30 10_51_47-LiteSpeed](https://user-images.githubusercontent.com/71660748/176636811-22c606d7-5302-4947-b628-8a35920e33f7.png)
I don´t know why this occurred, may be some update of the plugin, because it is with the default options since I installed it.
Thanks a lot and best regards!
