### ISSUE TITLE
Error while analyzing the PGN string. Unexpected end of text: there is a pending game.

### ISSUE THREAD

**Issue by yukkypoopoo** [yo35/rpb-chessboard#246]
Im having issues trying to setup a custom position.
Keeps showing different "Error while analyzing the PGN string. Unexpected end of text: there is a pending game."
![image](https://user-images.githubusercontent.com/59984543/181798823-1a673b1d-0b8e-49bf-85e4-dba06aca91e6.png)

The website where I am trying to place Game Block.  https://chessintaiwan.com/knowledge-base/test/
The lichess position that is providing me my FEN & PGN File https://lichess.org/analysis/5rk1/3q1p1p/5Q2/8/8/8/8/K7_w_-_-_0_1?color=white#8
![image](https://user-images.githubusercontent.com/59984543/181799271-7757bad6-0636-4291-8f73-ae97de8ab089.png)

The PGN text that doesn't work, even though I referred to your tutorial for Custom initial position.
https://rpb-chessboard.yo35.org/documentation/pgn-syntax/
and edited the PNG text accordingly 

![image](https://user-images.githubusercontent.com/59984543/181798450-18c06476-8198-4abd-bf33-c0e3181bc628.png)

I have tried changing Initial selection to : Beginning of the game, End of the game, Custom move, doesn't work either.
Please advise. Thanks!

[SetUp "1"]
[FEN "5rk1/3q1p1p/5Q2/8/8/8/8/K7 w - - 0 1"]

{[#]}

1. Qg5+ Kh8 2. Qf6+ Kg8 3. Qg5+ Kh8 4. Qf6+ Kg8

**Comment by yo35** [comment]
Each game in a PGN file must end with `1-0`, `1/2-1/2`, `0-1` or `*` (the latter meaning "no result"). Here, I guess that `*` is missing at the end of the game.

**Comment by yukkypoopoo** [comment]
YES ! 
It works now! 

[SetUp "1"]
[FEN "5rk1/3q1p1p/5Q2/8/8/8/8/K7 w - - 0 1"]

Qg5+ Kh8 2. Qf6+ Kg8 3. Qg5+ Kh8 4. Qf6+ Kg8*

**Comment by yukkypoopoo** [comment]
> Each game in a PGN file must end with `1-0`, `1/2-1/2`, `0-1` or `*` (the latter meaning "no result"). Here, I guess that `*` is missing at the end of the game.

`

**Comment by yukkypoopoo** [comment]
YES ! 
It works now! 

[SetUp "1"]
[FEN "5rk1/3q1p1p/5Q2/8/8/8/8/K7 w - - 0 1"]

Qg5+ Kh8 2. Qf6+ Kg8 3. Qg5+ Kh8 4. Qf6+ Kg8*

**Comment by yukkypoopoo** [comment]
> Each game in a PGN file must end with `1-0`, `1/2-1/2`, `0-1` or `*` (the latter meaning "no result"). Here, I guess that `*` is missing at the end of the game.

YES ! 
It works now! 

[SetUp "1"]
[FEN "5rk1/3q1p1p/5Q2/8/8/8/8/K7 w - - 0 1"]

Qg5+ Kh8 2. Qf6+ Kg8 3. Qg5+ Kh8 4. Qf6+ Kg8*
