### ISSUE TITLE
[Feature Request] Will rpb-chessboard be compatible with Elementor page builder?

### ISSUE THREAD

**Issue by yukkypoopoo** [yo35/rpb-chessboard#247]
Hey yo35, 

really appreciate the work you have already done! have sent a donation as gratitude.
Was wondering if compatibility with Elementor page builder is in the future roadmap?
As I haven't found a way to make this code show on Elementor page builder, even if I paste it in as shortcode or html.
Is there a way I can use your plugin without default Wordpress editor?

![image](https://user-images.githubusercontent.com/59984543/181905968-ab366f91-128d-47b0-ae56-6610bd5dfea8.png)

**Comment by yo35** [comment]
Sorry for the late reply.
I've never tried Elementor page builder. If it supports the standard WordPress shortcode mechanism, then it should work with RPB Chessboard. In this case, the syntax to insert a FEN diagram would be for instance:
```
[fen]r2qkbnr/ppp2ppp/2np4/4N3/2B1P3/2N5/PPPP1PPP/R1BbK2R w KQkq - 0 1[/fen]
```
... and for a PGN game:
```
[pgn]

[Event "Mtel Masters"]
[Site "Sofia, BUL"]
[Date "2005.05.12"]
[Round "1"]
[White "Anand, Viswanathan"]
[Black "Topalov, Veselin"]
[Result "1/2-1/2"]
[WhiteElo "2785"]
[BlackElo "2778"]
[WhiteTitle "GM"]
[BlackTitle "GM"]

1. e4 c5 2. Nf3 d6 3. d4 cxd4 4. Nxd4 Nf6 5. Nc3 a6 6. Be3 e6
7. f3 b5 8. g4 h6 9. Qd2 b4 10. Na4 Nbd7 11. O-O-O Ne5 12. b3
Bd7 13. Nb2 d5 14. Bf4 Nxf3 15. Nxf3 Nxe4 16. Qd4 f6 17. Bd3
Bc5 18. Bxe4 Bxd4 19. Bg6+ Kf8 20. Rxd4 a5 21. Re1 Be8 22. Nh4
e5 23. Rd2 a4 24. bxa4 Kg8 25. Bg3 d4 26. Rd3 h5 27. Bxe8 Qxe8
28. g5 Rc8 29. g6 Rh6 30. Rxd4 Rxg6 31. Nxg6 Qxg6 32. Rd2 Rc3
33. Red1 Kh7 34. Kb1 Qf5 35. Be1 Ra3 36. Rd6 Rh3 37. a5 Rxh2
38. Rc1 Qe4 39. a6 Qa8 40. Bxb4 h4 41. Bc5 h3 42. Nd3 Rd2
43. Rb6 h2 44. Nf2 Qd5 45. Be3 Re2 46. Rb3 f5 47. a7 Rxe3
48. Rxe3 Qb7+ 49. Rb3 Qxa7 50. Nh1 f4 51. c4 e4 52. c5 e3
53. c6 e2 54. c7 Qxc7 55. Rxc7 e1=Q+ 56. Rc1 Qe4+ 57. Ka1 Qd4+
58. Kb1 Qe4+ 59. Ka1 Qd4+ 60. Kb1 Qe4+ 1/2-1/2

[/pgn]
```

**Comment by yukkypoopoo** [comment]
Hey yo35, 

don't worry about the reply time, I am always grateful for getting a reply.
 
But FYI , even when I have compatibility settings on for FEN or PGN, the plugin doesn't seem to be able to show it. 
URL: https://chessintaiwan.com/knowledge-base/test/
 
A work around I have found, is that Lichess or Chess.com provide embedding tools for iframe, that I can use to embed on my website.
It's not bad, but I do still prefer using a native wordpress tool if possible.

**Comment by yo35** [comment]
With compatibility settings enabled, you must use `[fen_compat] ... [/fen_compat]` and `[pgn_compat] ... [/pgn_compat]` instead of `[fen] ... [/fen]` and `[pgn] ... [/pgn]`.

**Comment by yukkypoopoo** [comment]
Hey yo35, 

yeah, turning off the compatibility settings works fine now, thanks !
