### ISSUE TITLE
when I paste PGN in the chess game block it displays plain text

### ISSUE THREAD

**Issue by hecker4002** [yo35/rpb-chessboard#251]

**Comment by yo35** [comment]
Can you provide more information about your problem? Screenshot, the PGN with which you observe the issue, etc... ?

**Comment by hecker4002** [comment]
Here's the screenshot 👇

![Screen Shot 2022-11-16 at 17 52 09](https://user-images.githubusercontent.com/95535364/202244184-fb6067da-7485-4ed8-bdf3-5b5920e34c10.png)

I just pasted the PGN in the get started guide: 

[Event "Mtel Masters"]
[Site "Sofia, BUL"]
[Date "2005.05.12"]
[Round "1"]
[White "Anand, Viswanathan"]
[Black "Topalov, Veselin"]
[Result "1/2-1/2"]
[WhiteElo "2785"]
[BlackElo "2778"]
[WhiteTitle "GM"]
[BlackTitle "GM"]

1. e4 c5 2. Nf3 d6 3. d4 cxd4 4. Nxd4 Nf6 5. Nc3 a6 6. Be3 e6
7. f3 b5 8. g4 h6 9. Qd2 b4 10. Na4 Nbd7 11. O-O-O Ne5 12. b3
Bd7 13. Nb2 d5 14. Bf4 Nxf3 15. Nxf3 Nxe4 16. Qd4 f6 17. Bd3
Bc5 18. Bxe4 Bxd4 19. Bg6+ Kf8 20. Rxd4 a5 21. Re1 Be8 22. Nh4
e5 23. Rd2 a4 24. bxa4 Kg8 25. Bg3 d4 26. Rd3 h5 27. Bxe8 Qxe8
28. g5 Rc8 29. g6 Rh6 30. Rxd4 Rxg6 31. Nxg6 Qxg6 32. Rd2 Rc3
33. Red1 Kh7 34. Kb1 Qf5 35. Be1 Ra3 36. Rd6 Rh3 37. a5 Rxh2
38. Rc1 Qe4 39. a6 Qa8 40. Bxb4 h4 41. Bc5 h3 42. Nd3 Rd2
43. Rb6 h2 44. Nf2 Qd5 45. Be3 Re2 46. Rb3 f5 47. a7 Rxe3
48. Rxe3 Qb7+ 49. Rb3 Qxa7 50. Nh1 f4 51. c4 e4 52. c5 e3
53. c6 e2 54. c7 Qxc7 55. Rxc7 e1=Q+ 56. Rc1 Qe4+ 57. Ka1 Qd4+
58. Kb1 Qe4+ 59. Ka1 Qd4+ 60. Kb1 Qe4+ 1/2-1/2
