### ISSUE TITLE
Initial position

### ISSUE THREAD

**Issue by queribox** [yo35/rpb-chessboard#259]
Since every complete game starts with the same starting position, this is less attractive when opening a website showing multiple games

Is it possible to show a game from a latter position in the game (but including the whole game]. FEN seems not to do the job since then you completely skip the first moves. Or am I missing something?

What I try to accomplish is showing the following "opening-screen" when opening the post:
![Fragment](https://user-images.githubusercontent.com/129966758/230444336-56e32e3f-4cec-404f-81ed-5a3429c82149.jpg)

**Comment by yo35** [comment]
It's possible: see #205 for explanations on how to achieve that.

**Comment by queribox** [comment]
Thank you so far!
Since we are not using the Gutenberg-editor but the Classic Editor (for several reasons) I'm looking for the right way to enter the "initialSelection":"6w"
Is there a label you can use?

**Comment by yo35** [comment]
Unfortunately this feature is not available through the classic editor.

**Comment by yo35** [comment]
In fact, I notice that several users are still using the classic editor, thus it might be relevant to improve how RPB Chessboard integrates with this editor (and especially to port this feature).

**Comment by yo35** [comment]
As of RPB Chessboard 7.5.0 (just released), that would be available as:

```
[pgn initial_selection=6w]
...
[/pgn]
```
