### ISSUE TITLE
Bug: Duplicate diagram

### ISSUE THREAD

**Issue by paulotronik** [yo35/rpb-chessboard#262]
Hello,

This problem is popping up whenever I add markings to the diagrams or make a variation other than the starting position.

[img](https://i.imgur.com/f34ua3y.jpg)

**Comment by yo35** [comment]
Can you provide the PGN corresponding to this screenshot?

**Comment by paulotronik** [comment]
[pgn][SetUp "1"]
[FEN "1kb1r1r1/ppq5/2p5/3p1p2/2nP1N1P/PQR4P/KPB1N1P1/8 b - - 0 1"]

{[#]}

31... Rxg2 32. Nxg2 Rxe2 33. Ne3 Qh2 0-1[/pgn]

**Comment by yo35** [comment]
The 2nd diagram is due to the `[#]` token, as explained in https://rpb-chessboard.yo35.org/documentation/pgn-syntax/#diagrams. Remove it to get rid of the 2nd diagram.

**Comment by paulotronik** [comment]
Thank you very much.
