### ISSUE TITLE
Bug ? Floating diagram

### ISSUE THREAD

**Issue by JustEggbird** [yo35/rpb-chessboard#263]
When you have a floating diagram. You can sometimes close the diagram with the "escape" key. But sometimes not. It puzzled me. Why ?

**Comment by JustEggbird** [comment]
I see, you have to "click" inside the diagram, before closing. Not immediatly clear for everyone ....

**Comment by yo35** [comment]
More important: in the situation where the "escape" key works, the arrow keys do not work anymore.

**Comment by JustEggbird** [comment]
thanks

Van: Yoann Le Montagner ***@***.***>
Verzonden: vrijdag 26 mei 2023 18:29
Aan: yo35/rpb-chessboard ***@***.***>
CC: JustEggbird ***@***.***>; Author ***@***.***>
Onderwerp: Re: [yo35/rpb-chessboard] Bug ? Floating diagram (Issue #263)


More important: in the situation where the "escape" key works, the arrow keys do not work anymore.

**Comment by yo35** [comment]
Fixed in 7.5.4 (just released)
