### ISSUE TITLE
Custom start positions for Chess Games

### ISSUE THREAD

**Issue by rademakeronline** [yo35/rpb-chessboard#264]
I wonder, if it's possible to start a chess game with custom positions of the pieces. I tried with variations of the Chess960 examples but got errors for illegal moves.

If I did something wrong, I would be glad to hear, hoe to achive this. If it's not possible, I would be very happy, if this feature would be added.

Best wishes from Germany
Christian

**Comment by yo35** [comment]
Hi,
This is possible. An example is available here:
https://rpb-chessboard.yo35.org/documentation/pgn-syntax/#custom-initial-position

**Comment by rademakeronline** [comment]
Dear Yoann,

thanks for the support and the link.
