### ISSUE TITLE
The chess game block cannot be resized anymore

### ISSUE THREAD

**Issue by adclaran** [yo35/rpb-chessboard#267]
Hello,

Following the update to the new WP 6.3, the chess game block cannot be resized in editing mode (by the Admin). I used to resize that box to a much wider area. However, now that possibility no longer exists. There isn't a resizing handle in the bottom-right corner either.

Best regards!

**Comment by yo35** [comment]
In version 7.7.0, I've made the text area is larger. Still, it is not resizable anymore, as this component is managed by directly by WordPress (see for example the shortcode, that has the same text area component), and I guess this is the way the WordPress developers want it to behave.
