### ISSUE TITLE
RPB Chessboard works with which Wordpress templates?

### ISSUE THREAD

**Issue by benbog1** [yo35/rpb-chessboard#271]
My site is using GeneratePress and unfortunately this plugin doesn't work with it. But I'm willing to change the templates. So I want to ask you which Wordpress templates would work fine? Thank you.

**Comment by yo35** [comment]
Hi,

Should work with almost any theme.

In particular, following your message, I've tried with GeneratePress, and everything looks OK with it (cf screenshot below):

![generate-press](https://github.com/yo35/rpb-chessboard/assets/5740068/69ec2f01-bc60-47f0-a6e2-04e76a6fd182)

**Comment by benbog1** [comment]
When I pasted the PGN in to the block editor, it did not show up any board, like this. Do I have to install any plugins for GeneratePress to work?
<img width="1010" alt="Screenshot 2023-12-20 at 09 02 26" src="https://github.com/yo35/rpb-chessboard/assets/154314291/e847c127-4dff-4f28-9dc6-89199ff322c8">

**Comment by yo35** [comment]
The board appears only in the frontend, not in the page/post editor.

**Comment by benbog1** [comment]
Thank you. Not smart from me.
