### ISSUE TITLE
Custom initial position attributes

### ISSUE THREAD

**Issue by KingstonChess** [yo35/rpb-chessboard#272]
The attributes (e.g. flip=true) for game internal diagrams display are documented when using [fen]...[/fen]. However, when setting up a custom initial position using [FEN"..."] I cannot find the syntax to engage the attributes e.g. to flip the board for a custom initial position.

**Comment by yo35** [comment]
The syntax for `[pgn]...[/pgn]` shortcode attributes is the same as for `[fen]...[/fen]`.For instance, to flip the boards:

```
[pgn flip=true]

<The PGN text here>

[/pgn]
```

The list of all attributes supported by the `[pgn]...[/pgn]` shortcode is given on https://rpb-chessboard.yo35.org/documentation/pgn-shortcode-attributes/.

**Comment by KingstonChess** [comment]
Thanks, very helpful.
BTW my site has been under constant attack (450 failed logins in two days) since I posted the query on GitHub.
This is a disincentive to post queries on such a well known and public platform.
