### ISSUE TITLE
Shift position of variation

### ISSUE THREAD

**Issue by Ballintleave** [yo35/rpb-chessboard#276]
Typically a game write-up will deal with a variation and then move on to discuss a sub-variation. Readers like to reach the end of the variation before considering the sub-variation. However, sub-variations are presented immediately according to move order which disrupts the flow for the reader. 

Sometimes we want to consider a variation before the main move as with a missed opportunity e.g. "(White should have played 23 Rxe2!! ) but actually played 23.Bxc3"

Sometimes we want to consider a variation after the main move sequence e.g. "12.Bf4 Bf5 13.h3 h6 14.a3 (12.Bh6 would have avoided this repetition)"

The variants are shown in parentheses. (Removing some parentheses is a separate issue)

One way of implementing this could be to observe the move numbering. The variation would be shifted according to its numbering in the pgn.

**Comment by yo35** [comment]
Unfortunately, this is not compatible with the PGN format, cf spec: https://ia802908.us.archive.org/26/items/pgn-standard-1994-03-12/PGN_standard_1994-03-12.txt

See in particular section 8.2.5:
> The alternate move sequence given by a recursive annotation variation is one that may be legally played by first unplaying the move that appears immediately prior to the recursive annotation variation.

Also, from what I know, other softwares (typically Chessbase and SCID) do not interpret PGNs with misplaced variations the way you expect.

**Comment by Ballintleave** [comment]
Annotations are fuller now than in previous times. Hopefully PGN readers will recognise this trend and allow more flexibility for positioning the variants.
