### ISSUE TITLE
Start the game with blackside

### ISSUE THREAD

**Issue by TheChessForum** [yo35/rpb-chessboard#277]
I am loving this plugin, what i miss the must have feature is that, there should be a option to show black side by starting  just like flip button works,
I mean if there is a game from black side i want to show or position, there should be a default button to starting position (like start with white side by default or black side).
I hope you got what i mean.
Thanks

**Comment by yo35** [comment]
Both *Chess diagram* and *Chess game* blocks have a "flip" option to achieve that.

**Comment by TheChessForum** [comment]
How can i enable by default blackside option?

**Comment by yo35** [comment]
You cannot. Since the relevance of having the board flipped or not depends on the displayed game or diagram, it's not possible to have this option enabled by default. It's a per-block option only.

**Comment by TheChessForum** [comment]
Ok, thanks for the clarification.
