### ISSUE TITLE
Please add support for Numeric Annotation Glyphs $20 and $21 (White/Black has a crushing advantage)

### ISSUE THREAD

**Issue by pschneider1968** [yo35/rpb-chessboard#280]
First of all, thank you very much for this fantastic WP plugin! It works really well, and I just plain love it! 🙏

That said, I'd like to ask whether support for the NAGs mentioned in the title could be added? I use them a lot when I store and analyze my games in the Chess DB software Scid. So Scid export to PGN then, of course, contains $20 and $20, however this is not rendered at all in RPB-Chessboard plugin.

Please see these screenshots:

1) In Scid DB GUI

![grafik](https://github.com/yo35/rpb-chessboard/assets/36973164/58619d46-36a2-41aa-b7d7-2d0cc8077d89)

2) In PGN file

![grafik](https://github.com/yo35/rpb-chessboard/assets/36973164/c3b08fab-ddc4-4b84-9365-54ba910bdc5f)

3) In my WP website with RPB Chessboard plugin

![grafik](https://github.com/yo35/rpb-chessboard/assets/36973164/51bf0b24-4d5c-4395-b002-2f6cf2f40b16)

**Comment by yo35** [comment]
Hi,
This is available in version 7.9.0, just released.

**Comment by pschneider1968** [comment]
Wow, that's amazing - you are SO fast! Thanks a lot, I just upgraded, and it works nice 😀👍🙏🙏🙏
