### ISSUE TITLE
"Play" button?

### ISSUE THREAD

**Issue by DanijelDomazet** [yo35/rpb-chessboard#281]
Is there an option to add "play" button? 
In order to review a game of 50 moves, one has to click 100 times the "next" button.

**Comment by yo35** [comment]
Already requested in #91 . By the way, you can use the keyboard arrows or click on one of the move in the move list.

**Comment by DanijelDomazet** [comment]
Keyboard is not acceptable, especially on mobile devices.

I think this feature is crucial.
