### ISSUE TITLE
A problem with drag-and-drop function in pop-up navigation board when you watch sdiagram from mobile smartphone

### ISSUE THREAD

**Issue by SteinWurtcel** [yo35/rpb-chessboard#287]
Hi,
there is a little bug in displaying navigation board on mobile gaget - in pop-up navigation board mode.  When doing it on computer you can drag the board enywhere you want on the display. BUT you cant do the same when you use mobile devise. The navigation board with chess pieces appears in the center of the display and you cant drag it and move it left, right or to other sides. Just try to do this by yourself and will anderstand what i mean.
Thanks for plugin. Its realy the best.

**Comment by yo35** [comment]
Hi,
I'm aware of this issue. Unfortunately, this is a limitation of the jQuery-based popup container (you should be able to reproduce it on https://jqueryui.com/dialog/), thus there is nothing I can do to fix it.
