### ISSUE TITLE
Change pieceset

### ISSUE THREAD

**Issue by novindi** [yo35/rpb-chessboard#29]
Hey Yoann,

still like your plugin very much but I do have one question:

Is it possible to change the graphics of the pieceset to other common piecesets like Leipzig, Merida, etc?
And if yes do I have to make a new image of every piece on the board and overwrite the existing image in the /sprite folder or is there a better way to do this?

Maybe changing the way the pieces look is a nice feature for a future version of the pugin.
Thanks for your response!

Cheers,
Ivan

**Comment by yo35** [comment]
Hi Ivan,

Currently there is no "convenient" way to customize the piecesets. So yes, if you want to do this, you have to replace the files `bb.png`, `wb.png`, etc... in the sprite folder.

Each of these images is actually a montage of several square tiles with size ranging from 20 to 64 pixel width. If you work on Linux or Mac OS, there is a shell script (`render.sh`) in the sprite folder that could help you generating theses montages. However, if you work on Windows, you'll have to do this manually (or convert the script).

In the future, the plugin will provide more customization options! (already requested in #13) However, I don't know yet how distant is this future ! ;-)

**Comment by novindi** [comment]
Hey Yoann,

thanks for the quick reaction!
Oke I'll look into changing the image files and if that seems rather timeconsuming we'll just have to wait for one of your future releases... ;)

**Comment by friscodelrosario** [comment]
It looks easy enough to replace the various .pgn files for chess pieces, but what about the corresponding .svg files?

**Comment by yo35** [comment]
The `*.svg` files in directory `/css/sprite` are not directly used by the plugin. They are only used to ease generation of the corresponding `*.png` chess piece files (using the script `/css/sprite/render.sh`).

**Comment by friscodelrosario** [comment]
I substituted a set of different .png chesspieces, but render.sh couldn't find inkscape.

**Comment by friscodelrosario** [comment]
render.sh results in hundreds of lines like this:

** (inkscape-bin:57910): WARNING **: Can't open file: bb.svg (doesn't exist)

** (inkscape-bin:57910): WARNING **: Specified document bb.svg cannot be opened (does not exist or not a valid SVG file)

It seems replacing the pieceset will be an all-day hack.

**Comment by friscodelrosario** [comment]
It's necessary to change the file list in render.sh so "bb.svg" points to '/your/path/to/bb.svg'.

**Comment by friscodelrosario** [comment]
Processing file /Users/newhome/rpb-chessboard/css/sprite/wr.svg...
Background RRGGBBAA: ffffff00
Area 0:0:278.75:338.75 exported to 12 x 12 pixels (3.18819 dpi)
Bitmap saved as: tmp-12.png
Background RRGGBBAA: ffffff00
Area 0:0:278.75:338.75 exported to 13 x 13 pixels (3.45387 dpi)
Bitmap saved as: tmp-13.png
Background RRGGBBAA: ffffff00
Area 0:0:278.75:338.75 exported to 14 x 14 pixels (3.71956 dpi)
Bitmap saved as: tmp-14.png
mv: rename tmp-8.png to tmp-8-stack.png: No such file or directory
mv: rename tmp-9.png to tmp-9-stack.png: No such file or directory
mv: rename tmp-10.png to tmp-10-stack.png: No such file or directory
mv: rename tmp-11.png to tmp-11-stack.png: No such file or directory
mv: rename tmp-12.png to tmp-12-stack.png: No such file or directory
mv: rename tmp-13.png to tmp-13-stack.png: No such file or directory
mv: rename tmp-14.png to tmp-14-stack.png: No such file or directory
convert: unable to open image `tmp-*-stack.png': No such file or directory @ error/blob.c/OpenBlob/2617.
convert: unable to open file `tmp-*-stack.png' @ error/png.c/ReadPNGImage/3665.
convert: no images defined `/Users/newhome/rpb-chessboard/css/sprite/wr.png' @ error/convert.c/ConvertImageCommand/3032.
rm: tmp-*.png: No such file or directory

**Comment by yo35** [comment]
The script `render.sh` must be run from its own directory:
```
cd /path/to/rpbchessboard/css/sprite
./render.sh
```
But you must understand that in the first place this script is an helper for me to generate the chesspieces .png files. If you want to replace these files, you are free to not use this script and generate the replacement files by using your preferred image editor.

**Comment by yo35** [comment]
In order to make things more clear, starting from version 3.5.1, .svg files and `render.sh` have been moved from `/css/sprite` to `/assets/chess-sprites/`, which is a directory NOT packaged with the rest of the plugin (its content is only available through the GitHub repository).

**Comment by friscodelrosario** [comment]
~/rpb-chessboard/assets/chess-sprites()[master] ./render.sh
Processing file bb.svg...

** (inkscape-bin:25999): WARNING **: Can't open file: bb.svg (doesn't exist)

**Comment by yo35** [comment]
In version 4.3, it is possible to change the default color/piece themes. However, alternative themes must be chosen among the ones included with the plugin: users cannot build their own color/piece themes. This feature will be implemented in a future version.

**Comment by yo35** [comment]
As of version 4.5, users can create their own color/piece themes.
