### ISSUE TITLE
WP Plugin installed and activated, and up to date, but no block available, no FEN installed

### ISSUE THREAD

**Issue by fsmnerd** [yo35/rpb-chessboard#293]
Hi there,
I used RBP Chessboard for a little while now but since the last plugin update to 8.01 I get "No FEN installed" on all former defined blocks. Why?

I deactivated RBP, removed it, reinstalled it, but the problem is the same.

Any idea what I can do?!

Hans

**Comment by fsmnerd** [comment]
is there anyone at home?!

**Comment by fsmnerd** [comment]
Dashboard says, plugin is OK
![image](https://github.com/user-attachments/assets/c584179e-0fc0-4041-9f7d-d14f1761f89f)
Trying to find the block says No!
![image](https://github.com/user-attachments/assets/506cd598-5438-4506-919d-2d9a92bf9f9c)

**Comment by yo35** [comment]
What is the address of your website? Any example of a public page with one of these failing block?

And but the way, I would appreciate if remarks such as "is there anyone at home" could be avoided. The plugin is free, and this amount does not include a 24/7 support.

**Comment by fsmnerd** [comment]
First of all: please accept apologies for my comment!

As you can see, the website is based on chess, therefore displaying
chessboards essential, and my work for the chess community is on an
honorary basis for not just one decade. So when I get an inquiry I try
to reply as soon as possible, even though if I have to postpone any
further action.

Thus, my work is appreciated by a lot of chessplayers, and you can be
sure, I appreciate yours!

This is the website:

https:\\ks-karben.de

One page I'm having trouble with is:

https://ks-karben.de/thema/

while in posts the problem is the same. All chessboards are gone.

What is now missing can be checked when the attached pdf is opened. FEN
Display and "rpb-chessboard/pgn"- Block does no longer work.

As given in the post at the forum the plugin is installed and activated,
but the icons do longer appear in the Block manager (when adding a new
block etc). Even a search for "chess" fails.

This plugin stopped working properly after the plugin update I have made
a few days ago via dashboard.

Again, apologies! Please help....

Hans


Am 23.07.2024 um 12:07 schrieb Yoann Le Montagner:

**Comment by yo35** [comment]
My guess is that there is something weird with your theme... Until I find out the exact problem, you may rollback to version 8.0.0, following one of these procedures:
https://blogvault.net/wordpress-downgrade-plugin/
