### ISSUE TITLE
Game only showing when scrolling

### ISSUE THREAD

**Issue by Lea2002-del** [yo35/rpb-chessboard#294]
Hi, 

I added some Chess Games on this Website: https://sk-bebenhausen.schachvereine.de/?page_id=728

On Mobile the games are not showing. But when I scroll a bit, they become visible. I couldn't find a solution in the Settings. Without scrolling the site looks empty. This only happens on mobile devices. 

I use Elementor for my site.

**Comment by yo35** [comment]
Hi,
No time to investigate more thoroughly until the end of the month, but I guess this is a problem with your theme. I suggest you contact the theme maintainer.

**Comment by Lea2002-del** [comment]
Hi, 

thanks for your answer. After some testing it was the WP Meteor plugin that caused this issues.
