### ISSUE TITLE
Games are not displayed on web pages

### ISSUE THREAD

**Issue by juanparra64** [yo35/rpb-chessboard#295]
Hello.

I have been using RPB Chessboard for several years, and I think that due to some update all the games have disappeared from my website www.guapaweb.es. For example, on this page the game analyzed at the end of the page does not appear:
https://www.guapaweb.es/el-dia-que-fischer-cayo-ante-kovacevic/

The version of WordPress currently installed is 6.4.5. I always use the classic WordPress editor, first I upload the game in PGN to a WP folder, and then I insert the game in the classic RPB Chessboard format, for example, in this case:
[pgn_compat navigation_board=frame url="https://www.guapaweb.es/wp-content/uploads/2024/06/20240607FischerKovacevic1970.pgn" game=0][/pgn_compat]

All the games on my website are included this way, and all the games are no longer visible on the pages...

Best regards.

**Comment by yo35** [comment]
Hi,

Which version of RPB Chessboard is currently installed? By the way, your version of WordPress is quiet dated. I suggest to either upgrade your website to the latest WP version (6.6.1) or you downgrade RPB Chessboard to a version contemporary of your old WP (that would be RPB Chessboard 7.9.0 or 7.9.1 I guess).

How to downgrade a plugin is explained here for instance:
https://blogvault.net/wordpress-downgrade-plugin/

**Comment by juanparra64** [comment]
Hi.

I think it stopped working since I last updated RPB Chessboard to version 8.0.2. But I just updated WordPress to version 6.6.1 and everything is working fine again!

Thanks a lot and best regards!
