### ISSUE TITLE
There is no Save changes button in Theming

### ISSUE THREAD

**Issue by cuvno** [yo35/rpb-chessboard#297]
Hi.
There is no "Save changes" button in Theming. 
Is this a bug?

**Comment by yo35** [comment]
Hi,
In theming, you can create and edit colorsets and piecesets for the board. No global "save changes" button needed for that.

**Comment by cuvno** [comment]
Thank you for your reply.
I know I can create and edit.
But how do you commit the changes? What I want to know is how to reflect that.

**Comment by yo35** [comment]
There are *Create colorset* / *Create pieceset* / *Save changes* buttons to commit the changes. Which one is available depends on the context.

No other "change" to commit in the *Theming* section. The board on the right column is just a preview.

**Comment by cuvno** [comment]
Thank you, I understand.
