### ISSUE TITLE
When i have a very long pgn that wraps around the board buttons do not work

### ISSUE THREAD

**Issue by buffos** [yo35/rpb-chessboard#30]
For example in this page http://www.skakistis.gr/chesspuzzle/modern-benoni-with-bf4-part4/
the buttons do not work, but on http://www.skakistis.gr/chesspuzzle/modern-benoni-with-bf4-part3/ they work fine

Also it would be nice if keyboard worked

p.s  Actually if i make resize the browser and make is smaller. the buttons are accessible again.
It might have to do with z-indexing? i couldnt find the exact problem

**Comment by buffos** [comment]
I actually solved that by adding the following css
Just make the board's position relative so you can use z-index. and that's it.

/* put the board on top of notation */
.uichess-chessgame-navigationBox.uichess-chessgame-floatLeft {
	position: relative;
	z-index: 1000 !important;
  }

**Comment by richiwalt** [comment]
Cool site.  What plugin is doing the tabs for the articles ?

**Comment by yo35** [comment]
Not sure this issue is still relevant since it is quite old. Everything looks OK in the above-mentioned pages.
-> closing the issue, sorry if it went to the bug list limbos without any answer.
