### ISSUE TITLE
Diagram of chessgame is not shown

### ISSUE THREAD

**Issue by huubleeke** [yo35/rpb-chessboard#303]
Many chess diagrams of chessgames are no longer visible on our website (via Wordpress). The gamenotation is still visible.
Originally the chessdiagrams were visible. See https://www.dedrietorens.nl/terugblik-de-drie-torens-1/
What changed in the plugin that causes this problem? Current version Versie 8.0.2.
I attached tow files.
geme_good
[game_false.txt](https://github.com/user-attachments/files/17118059/game_false.txt)
[game_good.txt](https://github.com/user-attachments/files/17118060/game_good.txt)
 and game_false

**Comment by yo35** [comment]
What do you mean by _many chess diagrams of chessgames are no longer visible_ ? The chess games look OK for me, as shown in this screenshot:

![screenshot](https://github.com/user-attachments/assets/727ce619-1796-4367-9da6-d9969501798f)

**Comment by huubleeke** [comment]
Hi,

 

Thanks for your quick response.

In the first game the chessdiagram is visible.

But all the following games not.

For example, the second game Olree – Morren. 

This was a post of 2 years ago and then all the games started with a chessdiagram.

In the game-pgn there is a FEN that describes the starting position of the game (not begin position).

I do not see the difference between the two first games that I also attached to the issue.

 

I have the same problem with this pgn.

I exported the pgn from ChessBase.

The game-notation is visible, but not the chessdiagram.

 

[White "Weel, Jaap"]

[Black "Nieuwenhuijse, Louis"]

[Result "1/2-1/2"]

[SetUp "1"]

[FEN "1r1r2k1/p3n1bp/2bpq1p1/2pN1p2/4P3/1PN1B3/P1Q2PPP/2RR2K1 w - - 0 24"]

[PlyCount "3"]

 

{In deze stelling speelde Jaap een goede zet om zijn voordeel vast te houden, maar hij had een betere!} 24. Nxe7+ ({Meer voordeel was te bereiken met} 24. Bg5 $1 {Waarna zwart in alle varianten materiaal verliest} Bxd5 (24... Re8 25. Nxe7+ Rxe7 26. exf5 gxf5 27. Bxe7 Qxe7) (24... Bf8 25. Bxe7 Bxe7 26. exf5 gxf5 (26... Qf7 27. fxg6 hxg6 (27... Qxg6 $4 28. Nxe7+) 28. Nxe7+ Qxe7 29. Qxg6+) 27. Re1) 25. Nxd5 Nxd5 26. exd5 Qf7 27. Bxd8 Rxd8) 24... Qxe7 25. exf5 1/2-1/2

 

If you have more questions, please let me known

 

Thanks

Lee

 

Van: Yoann Le Montagner ***@***.***> 
Verzonden: dinsdag 24 september 2024 20:37
Aan: yo35/rpb-chessboard ***@***.***>
CC: huubleeke ***@***.***>; Author ***@***.***>
Onderwerp: Re: [yo35/rpb-chessboard] Diagram of chessgame is not shown (Issue #303)

 

What do you mean by many chess diagrams of chessgames are no longer visible ? The chess games look OK for me, as shown in this screenshot:

screenshot.png (view on web) <https://github.com/user-attachments/assets/727ce619-1796-4367-9da6-d9969501798f>

**Comment by yo35** [comment]
The difference is in the options of the chess-game block, as explained here: https://rpb-chessboard.yo35.org/examples/navigation-board/

**Comment by huubleeke** [comment]
Hi,

 

It works.

Thanks

Love your plugin.

Makes our website more interesting.

 

Thanks

Lee

 

Van: Yoann Le Montagner ***@***.***> 
Verzonden: dinsdag 24 september 2024 21:18
Aan: yo35/rpb-chessboard ***@***.***>
CC: huubleeke ***@***.***>; Author ***@***.***>
Onderwerp: Re: [yo35/rpb-chessboard] Diagram of chessgame is not shown (Issue #303)

 

The difference is in the options of the chess-game block, as explained here: https://rpb-chessboard.yo35.org/examples/navigation-board/
