### ISSUE TITLE
Include flip=true functionality in pgndiagram tag

### ISSUE THREAD

**Issue by friscodelrosario** [yo35/rpb-chessboard#32]
For the times we'd like Black on the bottom of a diagram, it would be convenient to have the "flip=true" switch from the [fen] tag for use inside the [pgndiagram] tag.

**Comment by yo35** [comment]
Hi,

The switch `flip=true` can already be applied on a `[pgn][/pgn]` tag: in this case, its effect is to flip all the diagrams in the corresponding game (and also the navigation board if any).

Initially, I thought that the switch `flip=true` on the `[pgn][/pgn]` tags would cover almost all the use cases, but seemingly this is not the case! ;-)

**Comment by yo35** [comment]
Done in release 3.5.1.
