### ISSUE TITLE
Update Problem

### ISSUE THREAD

**Issue by Sparhauoc** [yo35/rpb-chessboard#33]
When I updated to version 3.6 from version 3.5. (whichever the most recent version was), rpb chessboard no longer functioned. The code was still there, but not only were there no graphics, even the notation was just gone. I created a new page from scratch and copied/pasted your Paul Morphy example game, same thing. Then I noticed even in the settings the examples corresponding to the example code were missing.

I deleted the the plugin entirely and re-installed and its working again. Just thought you would like to know that somehow the update feature didn't work as it should, I had to delete and perform a clean install.

I'm using Fatcow's server by the way, and it may have been an issue with the update and their handling of PHP.

**Comment by yo35** [comment]
Hi,
Sorry that you encountered some problems during the plugin upgrade. However, the update mechanism is completely delegated to the WordPress engine, nothing is done by the plugin itself. It has been reported that plugin updates can fail under WordPress, but fortunately this is very uncommon (I've never encountered the case by myself).
