### ISSUE TITLE
"Insert/edit a chess diagram" tool doesn't work

### ISSUE THREAD

**Issue by mattlbailey** [yo35/rpb-chessboard#34]
When creating a new Wordpress page, the "Insert/edit new chess diagram" button doesn't do anything on click.  Shouldn't it open a window to set up a diagram?

**Comment by yo35** [comment]
Hi,
Indeed, the "Insert/edit new chess diagram" button is supposed to open a dialog, as shown by the 8th screenshot on https://wordpress.org/plugins/rpb-chessboard/screenshots/.

To help me guessing where the problem come from, can you:
1) Tell me more about the browser you are using? (IE/Firefox/Chrome/...? Version?)
2) Check whether or not you get javascript error messages when you click on the "Insert/edit new chess diagram" button? (to inspect javascript error messages on Firefox and Chrome: press F12, go on the "Console" tab, and then refresh the page)

**Comment by mattlbailey** [comment]
For some reason, it's working now.  But, thanks for your willingness to support!
