### ISSUE TITLE
Null moves aren't recognized.

### ISSUE THREAD

**Issue by squarology** [yo35/rpb-chessboard#35]
Edit: Showing a PGN game that starts at an FEN position DOES work but null moves aren't recognized by RPB which are written as double dashes. So my feature request is for RPB to recognize them.

This is the error message I get: Error while analysing a PGN string.
Unrecognized character or group of characters.
Occurred at position 588:
...59. c6 $1 -- 60. b5 -- 61. Rb7+ Kf6 62. c7 -- 63. b...
             ^

thank you and thanks again for the great plugin!

**Comment by yo35** [comment]
Done in version 3.6.1 (just made available). Please update the plugin. You may have to refresh the cache of your browser to make the update work.
