### ISSUE TITLE
How to add chessgame with navigation board

### ISSUE THREAD

**Issue by Wendigoo** [yo35/rpb-chessboard#36]
Hello,
I can add chessgame with popup board but not a navigation one like this
https://ps.w.org/rpb-chessboard/assets/screenshot-6.png?rev=1137943
Can you help me?
Thank you very much

**Comment by yo35** [comment]
Hi,

2 ways to proceed, depending on what you want to do:
- In the administration section of your WordPress site, menu "Chess" > "Settings", section "Position of the navigation board". This setting affects all the chess game on your website.
- Add a `navigation_board` attribute to the `[pgn][/pgn]` tag, for instance: `[pgn navigation_board=floatLeft] ... [/pgn]`. This will only affect the current chess game.

See in the administration section of your WordPress site, menu "Chess" > "Help" > "PGN game" for more details.
