### ISSUE TITLE
colored squares and arrows do not work

### ISSUE THREAD

**Issue by buffos** [yo35/rpb-chessboard#37]
Both in the help files (by the way returning in line 80 $this->getSquareSizeList()[1] is not supported in  earlier php versions and will fire an error) and in an example i tried it will not work

 [%csl Re5] is rendered as text comment (and all similar square and arrow tags)

**Comment by yo35** [comment]
Thanks for your report. I will submit a patch for the `$this->getSquareSizeList()[1]`-bug asap.

About `[%csl Re5] ` rendered as text in comment: you should force a refresh of your browser cache.

**Comment by yo35** [comment]
Done in version 4.0.1.

By the way, starting from this version, the browser cache should be automatically refreshed each time the version of the plugin changes.

**Comment by yo35** [comment]
Oups, there is a major bug in 4.0.1. Try version 4.0.2 instead.

**Comment by buffos** [comment]
It now works perfectly!
