### ISSUE TITLE
Highlight last move

### ISSUE THREAD

**Issue by mark30247** [yo35/rpb-chessboard#39]
When playing over a game the last move is shown on top of the board. It is however difficult to spot the complete last move, because only the target field is shown. It would be much easier, if the last played move could be highlighted somehow.

**Comment by yo35** [comment]
Hi,
I'm not really sure to get your point. What do you mean with "the complete last move" and "the target field"?

**Comment by mark30247** [comment]
Hi Yoann,

I hope I can make myself clear.

Lets say you have a move Bf1 - g5. Currently, after the move you only see
the bishop on g5. It is difficult to spot, what the last move was. On top
of the board you only see Bg5. I want the fields f1 and g5 to be
highlighted. Maybe, this can be an option like flip.

Regards,
Dirk



2015-07-22 11:19 GMT+02:00 Yoann Le Montagner <notifications@github.com>:

**Comment by yo35** [comment]
OK, I think I get your point. You would like to have the choice between different types of chess notation systems, as it is described in:
https://en.wikipedia.org/wiki/Chess_notation#Notation_systems_for_humans

In particular, you are interested in *long algebraic notation*, in which moves are written as `e2-e4`, `Bf1-b5`, `Nf3xd4`, etc... Am I right?

**Comment by mark30247** [comment]
No, the chess diagramm (popping up when you click a move) should show the
last move, just like the colored square.

2015-07-22 14:37 GMT+02:00 Yoann Le Montagner <notifications@github.com>:

**Comment by MatthewEppelsheimer** [comment]
I would like to see this, too. One way this could be built is a combination of two things:

1. Animate the transition of pieces from one square to another
2. After the transition animation in number 1 is complete, add an arrow pointing from the square the piece moved from to the square it moved to. This square would persist until the player's state changes to another move.

**Comment by yo35** [comment]
Done in version 4.2.

**Comment by mark30247** [comment]
Great. Thank you.

**Comment by MatthewEppelsheimer** [comment]
Thanks!
