### ISSUE TITLE
Arrowheads in Firefox but no arrowheads in Chrome 

### ISSUE THREAD

**Issue by squarology** [yo35/rpb-chessboard#40]
Hi, great upgrade to RPB. Currently I'm not seeing any arrowheads in chrome, but I am seeing them in Firefox. If anyone can give advice, I'd appreciate it. Obviously, I'll view the site in Firefox for now. Thank you.

http://i.imgur.com/MmUQmju.jpg

http://i.imgur.com/jT7ZWoP.jpg

**Comment by yo35** [comment]
Hi,
Thanks for your report. The fact that the arrowheads are not visible in Chrome is a bug. I will try to fix it as soon as possible.

By the way, in IE 8, arrows are not visible at all, but I do not plan to fix this bug (I don't want to spend to much time in making the plugin work with deprecated browsers). Everything looks fine in IE 9+.

**Comment by yo35** [comment]
Fixed in version 4.1.2.
