### ISSUE TITLE
Responsiveness lost in the new versions

### ISSUE THREAD

**Issue by squarology** [yo35/rpb-chessboard#41]
hi, Yoan, I noticed that RPB isn't responsive anymore.

eg http://mobiletest.me/iphone_5_emulator/?u=http://yo35.org/rpb-chessboard/live-demo/
http://mobiletest.me/samsung_galaxy_y_emulator/?u=http://yo35.org/rpb-chessboard/live-demo/

I've also checked it with one of my webpages.

**Comment by yo35** [comment]
Hi,
Good point. This is a bug introduced by the refactoring performed in version 4.0. I will fix that one.

**Comment by yo35** [comment]
Fixed in version 4.1.1.
