### ISSUE TITLE
Can't change navigation board mode, it seems stuck at popup-window

### ISSUE THREAD

**Issue by danjeln** [yo35/rpb-chessboard#43]
I cannot change the navigation board style under settings using IE11, i have several options available, but it cannot be changed. It works with chrome. Is this a known error?

**Comment by yo35** [comment]
Hi,

Thanks for your report. This is a new bug, that is specific to IE (no problem with other browsers). I will try to find a fix for it.

Meanwhile, it seems that you can change the navigation board style under settings by clicking a few pixels around the icons (see the screenshot below):

![screenshot_settings](https://cloud.githubusercontent.com/assets/5740068/9230886/58237d8c-4125-11e5-9689-982ba1905d4f.png)

**Comment by yo35** [comment]
Fixed in version 4.1.3.
