### ISSUE TITLE
What javascript function should be called to display RPB?

### ISSUE THREAD

**Issue by squarology** [yo35/rpb-chessboard#46]
hi, Yoann, could you please tell me what javascript function should be called to get the RPB chessboard to display?

The reason for this is that I'm using another plugin that uses ajax to display information and when it uses ajax it somehow bypasses the pgn shortcode. The plugin author told me that if I give him the javascript function he'll be able tweak his plugin so that RPB can display.

Thanks a lot for any help you can give me with this situation.

**Comment by yo35** [comment]
Hi,
You should have a look to my answer to issue #44 . Hoping it will help you.

**Comment by squarology** [comment]
thanks, Yoann.
