### ISSUE TITLE
Feature request - Multiple inline board

### ISSUE THREAD

**Issue by taxiIDZwaneveld** [yo35/rpb-chessboard#47]
I would love for the plugin to display inline chessboards on specific moves.
This would be great for publishing a match analisys.

For example,

[pgn] 1.e4 c5 2.Nf3 Nc6 3.d4 cxd4 4.Nxd4 e5 {Kalashnikov} (4 .... Nf6 {Svesnikov} 5. Nc3 e5 6. Ndb5 d6 {absoluut noodzakelijk} 7. Bg5 a6 8. Na3) 5.Nb5 d6 6.c4! (6.N1c3 Nf6{toch weer Svensnikov} ) 6...a6 7.N5c3 Nf6 [/pgn]

i would like to make a inline setup of the board from move 5.

This way you can write a good readable artical on a match in the PGN file.

**Comment by yo35** [comment]
Hi,

I'm not sure to understand what you want to do. Is it this:

```
[pgn] 1.e4 c5 2.Nf3 Nc6 3.d4 cxd4 4.Nxd4 e5 {[pgndiagram] Kalashnikov}
(4 .... Nf6 {Svesnikov} 5. Nc3 e5 6. Ndb5 d6 {absoluut noodzakelijk} 7. Bg5 a6 8. Na3)
5.Nb5 d6 6.c4! (6.N1c3 Nf6{toch weer Svensnikov} ) 6...a6 7.N5c3 Nf6 * [/pgn]
```
?

**Comment by yo35** [comment]
No answer for nearly two years... Closing the issue !
