### ISSUE TITLE
Adding keyboard control

### ISSUE THREAD

**Issue by yo35** [yo35/rpb-chessboard#48]
remlebarbare said:

> It would be nice to use keyboard arrows to navigate in the game when the board is focused.
> 
> Is keyboard control functionnality coming soon ?

**Comment by yo35** [comment]
Hi,
This is actually a good point. These functionality would greatly improve the plugin ergonomics.

**Comment by remlebarbare** [comment]
Hi !

Thx for the answers, if I find some free time, I will fork the code and submit a pull request. ;)

See you soon

**Comment by yo35** [comment]
Done in version 5.1.
