### ISSUE TITLE
Call pgn from url

### ISSUE THREAD

**Issue by yo35** [yo35/rpb-chessboard#50]
born61 said:

> hi,
> copy and past data pgn is hard
> can i call url of my data, like
> `[pgn data-url="mygame.pgn" /]`
> thanks

**Comment by yo35** [comment]
Hi,
Currently, it is not possible to load the PGN data from a distant URL. However, this may be a useful feature to add to the plugin.

**Comment by italianplayer** [comment]
well, yours is a nice plugin but to be the best you have to know what is at a chessplayer.
Here you can see a simple example looking at the source code
http://wpdev1.altervista.org/test/index.html
I hope the new version will come

**Comment by italianplayer** [comment]
a clarification: the batch file contains the standard format. it may contain several matches. currently the plugin handles no more games. matches are selectable from a select box
see example http://wpdev1.altervista.org/test/index.html
regards

**Comment by italianplayer** [comment]
hello , do you think to solve this request ? initially you could read the pgn locally . for the remote pgn there are problems of crossdomain ? you could make an asynchronous call to copy the pgn locally and then open it in the viewer . thank you

**Comment by yo35** [comment]
Hi,
Clearly, this feature is relevant, and will be implemented at some point in the plugin. Hopefully I will be able to work on it in the next weeks, but I cannot commit myself on a release date for this.

**Comment by italianplayer** [comment]
hello ,
 there's news about changing the plugin for this request ? load and select game from a local pgn files
thanks

**Comment by yo35** [comment]
This request is still in the to-do-list, but still it has no release date.

**Comment by italianplayer** [comment]
hello ,
there's news about request ? load data from a local file pgn
thanks

**Comment by yo35** [comment]
Hi,
Same status as 2 months ago: it will be done for sure, but no release date for now.

**Comment by yo35** [comment]
Done in version 4.7 (just released).

The syntax is `[pgn url="..." game=...]`. The attribute `game=...` allows to select which game in the targeted `.pgn` file should be displayed (use e.g. `game=0` for the first game of the file, `game=1` for the second, etc...).

Just a restriction: this feature does not (and will not!) work with cross-domain URLs, for security reasons. However, you can install a cross-domain proxy on your website to bypass this limitation (but it is your responsibility).
