### ISSUE TITLE
Not working on BuddyPress

### ISSUE THREAD

**Issue by janlwi971** [yo35/rpb-chessboard#52]
Everything works fine when you use this plugin on the posts or pages  of wordpress.

As soon as we try to include the chessboard in a BuddyPress post, I get an error message, and the chessboard is not shown : 
"Error while analysing a PGN string.
Unrecognized character or group of characters.
Occurred at position 0:"

**Comment by martinarean** [comment]
Hi!. Im trying to use BuddyPress with this plugin but in the replies inside a forum. I've already looking for hooks and filters and I think that I have to do that calling chessboard function. 
Any suggestion?

Thanks in advance!

**Comment by yo35** [comment]
Hi,
As of RPB Chessboard version 4.8.1 (just released), and assuming that the *bbPress – Do Short Codes* plugin is enabled (https://wordpress.org/plugins/bbpress-do-short-codes/), FEN diagrams should work in bbPress posts.

Unfortunately, the rendering of PGN games still does not work.

**Comment by martinarean** [comment]
Hi!, Thanks for the information. I'll waiting for the rendering of PGN in
next versions.

Regards

2017-04-23 12:59 GMT-03:00 Yoann Le Montagner <notifications@github.com>:

**Comment by yo35** [comment]
As of 2024, both the `[fen][/fen]` and `[pgn][/pgn]` shortcodes works in bbPress, though with the following restrictions:

1. The *bbPress – Do Short Codes* plugin (https://wordpress.org/plugins/bbpress-do-short-codes/) must be enabled - or any other plugin that achieves the same result, i.e. make the WordPress shortcodes be processed in bbPress forum messages.
2. Only messages posted by users with the ability to publish bbPress forums (i.e. probably only admins by default) are processed by *bbPress – Do Short Codes*. I don't know why this plugin has this restriction, nor how to override it through WordPress configuration. Still, that's a question for the author of *bbPress – Do Short Codes*.

An example of a bbPress forum with some chess content inserted with the `[fen][/fen]` and `[pgn][/pgn]` shortcodes:
![bbpress_example](https://github.com/yo35/rpb-chessboard/assets/5740068/edb1a6c3-706e-461a-b039-2289ad19c9ce)

**Comment by yo35** [comment]
Since the remaining problems are more related to *bbPress* and *bbPress – Do Short Codes* than to *RPB Chessboard* itself, I'm closing this issue.
