### ISSUE TITLE
This pgn don't work in WordPress

### ISSUE THREAD

**Issue by AjedrezPlus** [yo35/rpb-chessboard#53]
[pgn_compat navigation_board=floatLeft show_move_arrow=true flip=false]

[Event "British Chess Problems"]
[Site "Problemist - ecp007"]
[Date "1876.??.??"]
[Round "?"]
[White "Cotton, William C."]
[Black "#2 (publicado-098)"]
[Result "1-0"]
[Annotator "Ajedrez Plus"]
[SetUp "1"]
[FEN "8/1qN5/2pr4/2k1PB2/n1P5/1R2NK2/5B2/8 w - - 0 1"]
[PlyCount "3"]
[EventDate "1876.??.??"]
[EventCountry "ESP"]
[Source "Ajedrez Plus"]

{Diagrama [#]} 1. Bd3 Qxb3 (1... Qxc7 2. Nd5#) (1... Rd4 2. Ne6#) (1... Rf6+ 2. Nf5#) (1... Rg6 2. Nf5# (2. Nd1#) (2. Nc2#) (2. Ng2#) (2. Ng4#)) 2. Ned5# 1-0

[/pgn_compat]

The move 2. Ned5 does not work or I can not make it work well.

Can you help me?

The URL: www.ajedrezplus.com/?page_id=3956&amp;preview=true" target="_blank" icon="icon: exclamation-circle" size="6" background="#D43F3A"

**Comment by yo35** [comment]
Hi,
Thanks for your report. It does not work for me either, it seems to be a bug. I will try to fix it as soon as possible.

**Comment by yo35** [comment]
Fixed in version 4.2.3

**Comment by AjedrezPlus** [comment]
Perfect. Good job!!
