### ISSUE TITLE
pgn from stockfish does not work in rpb 

### ISSUE THREAD

**Issue by bobbishoen** [yo35/rpb-chessboard#54]
Good morning,

The FEN works perfect, but unfortunately I cannot copy a PGN-string from Stockfish.
1. Is it possible to tell me how implementing the PGN-games works? Simply [pgn] game [/pgn] doesn't work... 
2. I would like to add chess games with comments and sub variations, and encounter the same problem here when copying a PGN-string from Stockfish. Is the correct lettertype of any importance?

Regards,
Bob

**Comment by bobbishoen** [comment]
Additionally, I noticed that copying a PGN-string from Stockfish does work when I alter the 0-0 to the Consolas lettertype. This still leaves a new problem... 

Whenever I want to add a left screen image of a game, the control panel underneath is 'off' (too wide). Does anyone know how to solve this?

**Comment by yo35** [comment]
Hi,

There are several examples of how the `[pgn]...[/pgn]` tags work in the help section of the plugin: see in the admin part of your WordPress site > menu "Chess" > "Help" > "PGN game syntax".

There should not be any text formatting commands (bold, non-default font, etc...) in the PGN string, except in the text comments.

**Comment by bobbishoen** [comment]
Hi Yoann,

Thank you for your response! Love the plug-in by the way. Unfortunately, I have to change the font when importing a PGN string from Stockfish. The 0-0 is not read properly, but if I change the font to Consolas it does work. 
Also, I found the 'help'-page, and it is very instructive, but I do not see a solution for the arrows underneath the board. On my site, they are very wide as supposed to your original layout. Do you by any chance know of this problem?

**Comment by yo35** [comment]
The appearance of the buttons below the navigation board is determined by the theme you use for your website. If your are familiar with the CSS language, you can customize these buttons using the following code:

```
.uichess-chessgame-navigationButtons button {
    /* CSS code to customize the appearance of the navigation buttons */
}
```

**Comment by bobbishoen** [comment]
Dear Yoann,

Thanks for the reply, and also for the code. The layout works perfect! My
compliments for a great plug-in!

Kind regards,
Bob Bishoen
