### ISSUE TITLE
Having difficulty with O-O-O

### ISSUE THREAD

**Issue by patrickc3000** [yo35/rpb-chessboard#62]
How do I set the pgn/fen to allow for queenside castling?  I could not find it in the documentation and there should be no reason to receive the error "queen-side castling is not legal in the considered position".

Here is the code:

[pgn flip=true]

[Event "Tennessee Senior Open"]
[Site "Crossville, TN"]
[Date "2016.05.24"]
[Round "5"]
[White "Stoughton"]
[Black "Hayes"]
[Result "0-1"]
[Annotator "?"]

[SetUp "1"]
[FEN "r3k2r/pp1n1ppp/2pbpn2/q7/3P1B1N/8/PPP1NPPP/R2QR1K1 b - - 0 12"]
12...Bxf413.Nxf4 g5 14.Nxe6{14.b4 Qc7} fxe6 15.Nf3 O-O-O*[/pgn]

Thanks,
Patrick

**Comment by yo35** [comment]
Hi,
There is a mistake in the FEN position. Most likely, the correct line is:
```
[FEN "r3k2r/pp1n1ppp/2pbpn2/q7/3P1B1N/8/PPP1NPPP/R2QR1K1 b kq - 0 12"]
```
The additional `kq` indicates that the black king and the black rooks have never been moved before.

**Comment by patrickc3000** [comment]
Great, thanks for the help!

Patrick
