### ISSUE TITLE
condition that produces missing comment / out-of-order variation  in rendering the page:

### ISSUE THREAD

**Issue by richiwalt** [yo35/rpb-chessboard#64]
I have an article where I am narrating comments during chess plays ... and the following piece of WordPress code in the article:

----snippet of my code  start ----
23.a4 Rxd1 24.Rxd1 Rc8 25.Rd3 Qc6

{ IM Jack Peters chess columnist for the <em>Los Angeles Times</em> recommended:}

(25...Rc7 26.a5 Nc8)

{This holds on to his material for the time being, but Black's position still remains quite unpleasant.} 

26.Qxe5 Re8 27.Qd6 Nxe4 
----snippet of my code  end ----

The rendered page omits the comment:  "IM Jack Peters chess columnist for the <em>Los Angeles Times</em> recommended:"   

When the engine reaches this section of the code ... It shows as:

---- browser rendered page start ----
**23.a4 Rxd1 24.Rxd1 Rc8  25.Rd3 Qc6**
This holds on to his material for the time being, but Black’s position still remains quite unpleasant.

     25…Rc726.a5Nc8

**26.Qxe5Re827.Qd6Nxe4**

----- browse rendered page end -----

Notice there are TWO bugs here:

(1) missing the first comment in braces does not display:  "IM Jack Peters chess columnist ... "

(2) The order of the optional vibration comes AFTER the second comment.  In the code it appears BEFORE the second comment.  

If I am doing something wrong ... please let me know ... 
thanks,
Richard

BTW ... I really LOVE this plugin ...

**Comment by yo35** [comment]
Hi,

The plugin has a limitation, that is only one text comment is allowed per move. In your example, both comments "IM Jack Peters ..." and "This holds on ..." are associated to move `25...Qc6`, therefore the second comment overwrites the first one.

I suggest you put the comment "This holds on ..." within the variation to fix the problem. That is:

```
23.a4 Rxd1 24.Rxd1 Rc8 25.Rd3 Qc6

{IM Jack Peters chess columnist for the Los Angeles Times recommended:}

(25...Rc7 26.a5 Nc8 {This holds on to his material for the time being,
but Black's position still remains quite unpleasant.})

26.Qxe5 Re8 27.Qd6 Nxe4 
```

**Comment by richiwalt** [comment]
First thanks so much and that certainly helps. But for what it's worth I did the same thing with two comments and an alternate variation previous to this and it seem to work fine. Weird!

But at least I know what it's limitations are. Is there a documentation that I can get all of the limitations and things like that so I'm not surprised in the future?

But I love it there doesn't seem to be anything that comes close as far as documenting a game !!!
:-)

Richard.   

( Please forgive any spelling errors ... This email was sent from a mobile device. )

**Comment by richiwalt** [comment]
Close this one.   Works fine if one comment per move as you say.   Your suggestion with second comment inline of variation  also works fine as well.

**Comment by richiwalt** [comment]
I have looked and looked.

What changes do I need to make to the following code in order to see this diagram from the viewpoint of Black’s position ?     

[pgn]
[SetUp 1]
[FEN "1KR4R/PPnQN1PP/5P2/q1B5/5b2/4p3/p2P1ppp/1r2k2r b - - 0 1"]
{[pgndiagram] black to move}

0-1
[/pgn]


thanks,

**Comment by richiwalt** [comment]
Sorry yo35, 

Ignore my last … hope I did not waste too much of your time.

figured it out … it’s in the [pgn] tag … not the fen tag.   :-)

LOVE this plugin … making good use of it.

Thanks Again,

Richard

**Comment by richiwalt** [comment]
Hello,

Castling errors from a custom setup with a [FEN ...] definition ...

Here's my code:


[pgn]
[SetUp "1"]
[FEN "r1bqr1k1/1p1nb2p/p1p1ppp1/2Pp3n/3P4/P1N1PN1P/1P2BPPB/2RQK2R w KQ - 0 1"]

{[pgndiagram]<em>Silman-Barkan, U.S. Open 1981<br>White to play.</em>

<br>White enjoys a clear space advantage on the queenside. Normally the first player might try to add to this by b2-b4 and a3-a4, followed by an eventual b4-b5.

<br>However, it is not enough to look at your own plans to the exclusion of the opponent's. Just what <em>is</em> Black to do? Apparently, he will attempt to advance the center with ...Bf8 and ...e6-e5 (thus annexing territory of his own). Why should White allow this? Why not take space everywhere and leave Black with little or no counterplay? This is the reasoning White employed when deciding on his next move.}

1.e4

{<br>Grabbing a spatial plus in the center. Now White would welcome 1...dxe4 since 2.Nxe4 would allow him to make use of the d6-square and, once White castles and places a Rook on e1, the backward pawn on e6. This move shows us that it is not enough to simply recognize a space advantage. You must also be able to <em>create</em> extra territory; don't expect it to magically appear.} 

1...Bf8 {<br>}
2.O-O
1-0
[/pgn]


The moves below are purposely left out of the code above, but I'd like to insert the following moves when it's fixed.  

2...Bh6 {<br>}
3.Rc2 Kh8 {<br>}
4.Re1 Nf4 {<br>}
5.Bf1 Rg8 {<br>}
6.b4

=====

Errors:

(1) move one is only valid if the castle field is a perfect dash.  Otherwise, if it's KQ, I get an error for move one.   

(2) I need to annotate a castle on move two of white, but I can not figure any way to do this with any combination for the castling rights in the FEN header.   

What am I doing wrong ?




Please forgive any spelling errors as this message was sent from a mobile.

**Comment by yo35** [comment]
Hi,

In your case, the castle field cannot be "KQ" as there is no white rook 
on a1 (hence queen-side castling is not legal for White). With "K" 
instead of "KQ", your code works.

However, I admit the error message is quite unclear!  ;-) I will try to 
improve this in the next version.

**Comment by richiwalt** [comment]
Thanks ... I actually figured that out about 5 mins after my email (although I spent about 3 hours reading fen rules and trying different combinations before that).   I knew black had lost castle rights.   

I then quickly logged into github and found where my email went and deleted my post.  So sorry for wasting your time.  

Thanks again for the plugin - pretty awesome !!!! 


( Please forgive any spelling errors ... This email was sent from a mobile device. )
