### ISSUE TITLE
Ability to use RPB Chessboard with bbpress?

### ISSUE THREAD

**Issue by drgibbon** [yo35/rpb-chessboard#65]
I wonder if it would be easy to integrate RPB Chessboard with [bbpress](https://bbpress.org/)? I'd like to users to be able to post FENs and PGNs in bbpress threads using the [fen]/[pgn] shortcodes, and have them displayed just like they would be on a post or page.

**Comment by yo35** [comment]
Hi,
I've never tried to used RPB Chessboard with bbPress. (actually I'm not familiar with bbPress at all!) I'll have to try this plugin to see whether it is possible or not.

**Comment by drgibbon** [comment]
Did you manage to find out if this is possible at all? Would make for a great addition to our club's website :)

**Comment by yo35** [comment]
Hi,
From what I've seen, bbPress does not support shortcodes defined by third-party plugins in forum posts, but I do not master all the technical subtleties of bbPress. I've requested technical support on their forum:
https://bbpress.org/forums/topic/third-party-shortcodes-in-bbpress-posts/

**Comment by yo35** [comment]
Hi,
As of RPB Chessboard version 4.8.1 (just released), and assuming that the *bbPress – Do Short Codes* plugin is enabled (https://wordpress.org/plugins/bbpress-do-short-codes/), FEN diagrams should work in bbPress posts.

Unfortunately, the rendering of PGN games still does not work.

**Comment by drgibbon** [comment]
Thanks for this! I will test it out.

**Comment by BrendanJNorman** [comment]
Hi,

Very interested in embedding PGNs in my bbpress posts too.

Any updates on compatibility?

**Comment by yo35** [comment]
Hi,
Unfortunately, no update on this feature yet.

**Comment by BSEChess** [comment]
I realise this thread is rather old, but I figure it may be useful to keep all the related stuff together. Am I doing something wrong or does this no longer work?

You'd never said that PGNs worked, but I can't get FENs working in bbPress either. Using "inspect" reveals the javascript error:

`Uncaught TypeError: $(...).removeClass(...).chessboard is not a function`

Looking at other issues people have encountered this looks like it's a compatibility issue with plugins or themes, but I've put up a test version of the site and deactivated all the plugins other than bbPress, bbPress Do Short Codes and RPB Chessboard. I've also tried switching to the standard themes and I still get that error and no board. My debugging abilities are rather limited, so I don't know what else to look for.

The test site with the non-working bbPress post and replies is [here](http://s642149839.websitehome.co.uk/discuss/topic/test-puzzle)

**Comment by yo35** [comment]
@BSEChess FEN rendering in bbPress has been broken because of optimizations made for #135.

As of version 5.7.0, a workaround is provided: go to the plugin compatibility settings (in admin, menu "Chess" > "Settings" > "Compatibility settings"), and disable "Lazy-loading for CSS/JavaScript files").

PGN still does not work in bbPress.

**Comment by yo35** [comment]
As of 2024, both FEN and PGN are working in bbPress, though with some restrictions. More details in #52.

**Comment by yo35** [comment]
Since the remaining problems are more related to bbPress and bbPress – Do Short Codes than to RPB Chessboard itself, I'm closing this issue.
