### ISSUE TITLE
FEATURE REQUEST:  Animate the next move after a CUSTOM setup position.

### ISSUE THREAD

**Issue by richiwalt** [yo35/rpb-chessboard#68]
In most of my articles, I often start a game from a CUSTOM SETUP position  (and I do display a diagram of that starting-position with the [pgndiagram] short-code) ... and then I will go on to list multiple moves after the custom position  

However, when the reader clicks on the first move's link - and the PopUp chessboard that walks though the game appears -  they often do not recognize (visually) what piece _just moved_  to reach that position.  (There's no animation of that first move). The reader has to look at the move, then look back at the first pgndiagram image and find where the image was before -OR - hit the back button, and then hit the forwards button to see the piece move. 

Is it possible to automatically animate the piece movement from the previous position to the current position when the board first opens, if not from the start of the game?  I.e, when one clicks on the link in the middle of a game, instead of showing that static "current position", can we start with the previous position, and immediately animate the piece that moves on the current position ?  Is this possible without too much coding effort ?

It would be a nice improvement if so ... 

thanks in advance for considering this request.

**Comment by yo35** [comment]
Agree on this request.

**Comment by yo35** [comment]
In fact, it's more a bug than a feature request... Fixed in version 4.3.3.
