### ISSUE TITLE
Close "X" icon for popup style board moved in 4.3.3

### ISSUE THREAD

**Issue by richiwalt** [yo35/rpb-chessboard#69]
I much prefer the latest version, 4.3.3,  to the previous version 4.3.2 - as I like the animated "Last Move" when popping a mid-game link ... 

but I noticed that this last version, 4.3.3,  displays the close icon ( the "X") immediately following the window's _move-title_ on the upper left side ....  the X close icon used to be in the standard upper-right-corner.   

Hope that's not too much trouble to fix ... doesn't really bother me all that much ... but it's rather non-standard, and not what folks are used to seeing for the standard close position.

Hope this post is easy to read and understand ...

**Comment by yo35** [comment]
Hi,
It is strange that version 4.3.2 and 4.3.3 show different behaviors on this feature, as there is really little differences between both versions, and positioning of the close button is not directly achieved by the plugin.
If you've upgraded your theme or your WordPress at the same time as the plugin, it could explain this behavior.

**Comment by richiwalt** [comment]
Yep,  after troubleshooting, I see that **Tabs Responsive** plug in was added, and seems to break the placement of the close button of the popup chessboard ...

So ... I've changed a few articles to use that plugin ... turning multiple articles into tabbed ones.   Not sure where to go from here.  This looks to be a fairly nitchy bug of compatibility ... 

Suggestions ?

**Comment by yo35** [comment]
Answered here:
https://wordpress.org/support/topic/tab-responsive-rpb-chessboard-compatibility-issue?replies=9

> It looks like a compatibility issue between 2 JavaScript libs: Bootstrap (brought by Tabs Responsive) and JQuery UI (brought by WordPress and used by RPB Chessboard).
> 
> More precisely, there is a naming conflict as both JS libraries defines $.fn.button. See:
> https://github.com/twbs/bootstrap/issues/6094
> 
> My opinion is that Bootstrap should be loaded "no conflict" mode enabled, i.e. jQuery.fn.button.noConflict() should be called after loading Bootstrap.

**Comment by richiwalt** [comment]
If anyone else is having this issue due to a conflict with Tabs Responsive plugin, then I have a fix for you.  It's a simple file replacement in the Tabs Responsive directory that corrects the close button placement and style in JQuery. Just ping this thread and I'll get it to you. 

Tabs Responsive will not be adding this fix to their plugin ... But to their credit, they did fix it for me ...

thanks,

Richard

**Comment by yo35** [comment]
As of version 5.1.4, the `jQuery.fn.button.noConflict() ` workaround can be directly enabled by RPB Chessboard. To enable it, go to the admin pages, "Chess" > "Settings" > "Compatibility settings", and select "Try to fix jQuery's buttons".
