### ISSUE TITLE
Arrowheads don't show up in chrome

### ISSUE THREAD

**Issue by squarology** [yo35/rpb-chessboard#71]
Check out http://rpb-chessboard.yo35.org/chess-game-with-comments-and-sub-variations/ on a chrome web browser, the arrowheads don't show up. Any help would be greatly appreciated!

**Comment by yo35** [comment]
Hi,
Works for me, with Chrome version 51.0. Which version of Chrome do you have?

![arrows in Chrome](https://cloud.githubusercontent.com/assets/5740068/18064271/ed66f81a-6e2e-11e6-8b7e-4d01c5e2e27a.png)

**Comment by squarology** [comment]
That's so weird, today I checked and it's working. Sorry!
