### ISSUE TITLE
[REQ] change [pgn] and [/pgn]

### ISSUE THREAD

**Issue by maximuss22** [yo35/rpb-chessboard#73]
I have another plugin that use

[pgn] and [/pgn]

I'd like to use rpb-chessboard for my new post, but I don't' want to change my old post output.

How can I change with
[pgnRPB] and [/pgnRPB] and use rpb-chessboard together yo my old plugin?

thank you
Max

**Comment by yo35** [comment]
Hi,
To make RPB Chessboard work with another plugin that uses the `[pgn][/pgn]` shortcode, you should go on the page "Settings > Compatibility with other chess plugins" and enable the "Compatibility mode for PGN" option.
