### ISSUE TITLE
PopUp

### ISSUE THREAD

**Issue by maximuss22** [yo35/rpb-chessboard#75]
Hi

I use Rpb-chessboard plugin Version 4.6 in this site

http://demodimax.altervista.org/maxwp/test-rpb-chessboard/

but Popup function is not available

If I press, for example move 13, I see the move in the chessboard.

I note that your Demo webpage
http://rpb-chessboard.yo35.org/chess-game-with-comments-and-sub-variations/

popup works when I press a move.

What is the different?

I use this code

La partita del mese 

[pgn_compat]

[Event "Segrate 2016-2017"]
[Site "?"]
[Date "2016.09.29"]
[Round "1"]
[White "Stefano"]
[Black "Cristina"]
[Result "1-0"]
[ECO "D53"]
[PlyCount "71"]
[EventDate "2016.??.??"]

1. d4 d5 2. c4 e6 3. Nf3 Nc6 4. a3 Nf6 5. Bg5 Be7 6. Nc3 O-O 7. e3 Ne4 8. Nxe4
dxe4 9. Bxe7 Nxe7 10. Ne5 f6 11. Ng4 f5 12. Ne5 c6 13. Be2 Qe8 14. O-O Ng6 15.
Bh5 Rf6 16. Qc2 b5 17. f3 exf3 18. Rxf3 Bb7 19. Rg3 Rd8 20. c5 a5 21. b4 a4 22.
Rd1 Bc8 23. Bxg6 hxg6 24. Qf2 Kf8 25. Qf4 Ke7 26. Qh4 Kf8 27. Qh8+ Ke7 28.
Qxg7+ Rf7 29. Nxg6+ Kd7 30. Ne5+ Ke7 31. Qg5+ Kf8 32. Nxf7 Qxf7 33. Qh6+ Ke8
34. Rg7 Qf8 35. Qg6+ Qf7 36. Qxf7# 1-0

[/pgn_compat]

thank you
bye Max

**Comment by yo35** [comment]
Hi Max,

You cannot have the popup frame (as in http://rpb-chessboard.yo35.org/chess-game-with-comments-and-sub-variations/) and the navigation board (as in http://rpb-chessboard.yo35.org/navigation-board/) at the same time. The plugin has been designed like this because both the popup frame and the navigation board carry the same information.

**Comment by maximuss22** [comment]
can you give me instruction to have popup frame?

Anyway I don't found in help page full parameter to put after [pgn_compat]

Thank you
Max

**Comment by yo35** [comment]
Well, two solutions:
- Either you set the "position of the navigation board" option to "in the popup frame" (see the "settings" page in the administration part of your website). In this case, this setting will affect all the `[pgn_compat] ... [/pgn_compat]` sections of your website.
- Or you define your PGN section as follows:
```
[pgn_compat navigation_board=frame]
...
[/pgn_compat]
```
(only this section will be affected in this case)

**Comment by maximuss22** [comment]
Now Popup works on web site
http://demodimax.altervista.org/maxwp/test-rpb-chessboard/

I use
[pgn_compat navigation_board=frame]
...
[/pgn_compat]

can you help me about this?

>Anyway I don't found in help page full parameter to put after [pgn_compat]

thank you 
Max

**Comment by yo35** [comment]
In the administration part of your website:

Menu "Chess" > Sub-menu "Help" > Page "`[pgn_compat][/pgn_compat]` tag attributes"

**Comment by yo35** [comment]
No answer since November 2016 => I close the issue.
