### ISSUE TITLE
feature request: export PGN or FEN

### ISSUE THREAD

**Issue by gomasch** [yo35/rpb-chessboard#78]
Hi, 
it would be great to have simple PGN export from within the UI. This would allow to copy the game  and feed it into an external (online) analysis engine quickly. A more simple version would be to allow exporting the current position in FEN notation for the same purpose.
Btw. great work!
Best Regards
Martin

(edit: With some custom JavaScript around it I achieved the PGN export on my micro blog now on my own. While it might still be a good idea to have this, the original requester (me) is not waiting for it for anymore :). Thanks anyway!)

**Comment by yo35** [comment]
PGN export is now available in RPBChessboard 5.0 (just released).
