### ISSUE TITLE
Pgn diagrams doesn't shown correctly in IE11

### ISSUE THREAD

**Issue by Eslanecek** [yo35/rpb-chessboard#80]
Hi,
 **RPB-Chessboard is not working correctly in IE11** - see attached screenshot.

It's working ok in other browsers, e.g. FF or Chrome.
The complexity of pgn doesn't matter, I tested it also for simple short pgn without any additional tags and comments, the issue is still the same.

Any help highly appreciated! ;-)
Thanks.

**URL:** https://www.usk-sachy.cz/2017/03/praha-4-a-usk-c-jak-dopadneme-proti-favoritum-na-postup-snehulak-to-snad-nebude/#more-9440

**Error in IE11:**
![chybapgnie11](https://cloud.githubusercontent.com/assets/26333265/23809893/a0d73bca-05cf-11e7-8811-ba3d822febb2.jpg)

**The same Pgn is ok e.g. in Chrome:**
![pgnokchrome](https://cloud.githubusercontent.com/assets/26333265/23809898/a4fa9aa8-05cf-11e7-9a12-5f2e98879ae4.jpg)

**Comment by yo35** [comment]
Hi,
Strange bug... Could you send me one of the PGN file for which you observe the error? (please send me the PGN file itself, without copy-pasting anything)

**Comment by Eslanecek** [comment]
Hi yo35, 
thanks for the quick reply.
I don't have the original pgn (I'm not the author of the article), but I can try to get it from my colleague later. But anyway, I attached the whole wordpress article together with pgn. I also tried to create new one pgn - just for testing purposes, without any additional tags, only with one move. You can see it in the same URL as mentioned in the description, just scroll down - you will see both games correctly shown in chrome, but you will see the same error in IE11 again - see screenshot.
Thanks,
Al

[wp-pgn.txt](https://github.com/yo35/rpb-chessboard/files/836784/wp-pgn.txt)
![2017-03-12 19_06_34-usk praha praha 4 a usk c jak dopadneme proti favoritum na postup_ snehulak](https://cloud.githubusercontent.com/assets/26333265/23834576/19ceb5f0-0759-11e7-90e7-e02f4c521547.jpg)

**Comment by Eslanecek** [comment]
Hi, so the original pgn attached as well,
Thanks for your investigation,
Al.

[Uhliházi-Hájek.zip](https://github.com/yo35/rpb-chessboard/files/839591/Uhlihazi-Hajek.zip)

**Comment by yo35** [comment]
Hi,
I've found out the problem: it does not come from the PGN, but from the following tag in the header of your webpages:
```
<meta http-equiv="X-UA-Compatible" content="IE=EmulateIE7" />
```
This tag tells IE (whatever its version) that the corresponding pages should be rendered as it used to be in IE 7.0. More details here: https://msdn.microsoft.com/en-us/library/ff405803(v=vs.85).aspx

I don't know why there is this tag is your webpages. (Is it really necessary for your website to emulate the old IE-7 behavior for legacy purposes?) But the point is that RPB Chessboard requires at least IE-9. Unfortunately, it is too much work to make it compatible with the older versions of IE.

**Comment by Eslanecek** [comment]
Hi yo35,

**thanks a lot for your investigation and time!** I'm glad we know the reason of the issue.
I will discuss this problem with admin of our web-pages.
Very good job!
Have a nice day,
Al.

**Comment by Eslanecek** [comment]
**Confirmed - It works!**
I have updated the header of our web and the issue is solved!
Once again, thanks a lot for your help, yo!
Al.
