### ISSUE TITLE
Aligning FEN left or right in posts

### ISSUE THREAD

**Issue by smittySKHG** [yo35/rpb-chessboard#81]
Thank you for this wonderful and easy to use chessboard-plugin. 

Currently, every [FEN]-Shortcode results in a centered chessboard in an own paragraph. It would be nice to include such a board left or right-aligned in the text flow. An attribute to the shortcode [FEN align = "left"] could be appropriate. 

Currently, I have the following workaround: 
- Surround the [FEN] xxx [/FEN] by `<table align = "left"><tr><td>`  and `</td></tr></table>`. 
- and I even extended my copy of rpb-chessboard with to new shortcodes [FENL] and [FENR] encapsulating the table-trick above. 

But both workarounds are not to the point of WordPress, the latter is problematic while updating to a new version and both are not supported by the diagram editor of rpb-chessboard, of course.

Best regards, 

Walter

**Comment by yo35** [comment]
Done in version 4.8 (just released).
