### ISSUE TITLE
Possible to have Chess Alpha pieces?

### ISSUE THREAD

**Issue by squarology** [yo35/rpb-chessboard#82]
Hello, Yoan, Is it possible to have Chess Alpha pieces by Eric Bentzen? http://www.enpassant.dk/chess/fontimg/alpha.htm It's free for educational use. If you think it's possible and you need any assets then you can let me know so that I can pass them on to you. I think that I read you had some way of creating those PNGs with a script or something like which is why I ask.

Thanks for your attention.

**Comment by yo35** [comment]
Hi,
As of version 4.5, it is possible to create custom sets of chess pieces. In the admin zone, go to "Chess" > "Theming" > "Pieceset" > "Add a new pieceset", and then upload the 14 square images that will be used to generate the custom pieceset.
