### ISSUE TITLE
iPad Issue ... Request Info

### ISSUE THREAD

**Issue by richiwalt** [yo35/rpb-chessboard#83]
Love this plugin  .... but a question right quick ... seeking suggestions:

When I view a WordPress article with this Chess plugin on my 12.9" iPad pro (or any iPad for that matter) ... the popup board comes up in the exact center.  And, on iPad, there seems to be no way to "grab the window" to move it to an offset position (i.e. move it to the side somewhere ) to follow the article's comments about the position.

Recently this problem has gotten even worse.  How to put this into English words ... Use to ... I would zoom in on the page, and the floating JavaScript window would also get larger, but start to magnify in a way that repositioned it off from the center ... I could just zoom-in in order to "relocate it to the side".  Now, However, zooming seems to have changed ... it just makes both the background and the floating JavaScript window get larger ... the JavaScript board still stays PERFECTLY in the center.   

Is there a way to offset the displayed board ?   Who would fix that ?  Apple ?  Is it possible to get control of that location (or to have **iPad offset options** of where that pop up window is displayed ?  

Thanks for any help, suggestions ...

-richard

**Comment by yo35** [comment]
Hi,
Moving the popup is achieved by dragging its title.

I've no Apple hardware to try this by myself. However, the popup board is displayed using a jQuery UI component, which is quite common. You can check whether it works with your iPad or not on the following page: http://jqueryui.com/dialog/.

**Comment by yo35** [comment]
This issue is 3 year old now... Closing it.
