### ISSUE TITLE
'The position is not legal' error

### ISSUE THREAD

**Issue by Mohankrish01** [yo35/rpb-chessboard#86]
I have used the below PGN string but the preview says invalid move. 
[pgn]
[FEN "1r4k1/b2b1Rpr/p2P3p/1ppB4/8/2B5/PP1q1PPP/2R3K1 w Qq - 0 1"]

1. Rxg7+ Kh8 2. Rg8#1-0

[/pgn]

Screenshot: [http://www.awesomescreenshot.com/image/2406299/ded5f94df70358b0a5fc54627ac3b7da](url)

I generated this move from lichess editor and it used to work for many moves but not for all. Please help me to figure out the issue.

**Comment by yo35** [comment]
Hi,
The right FEN is: `1r4k1/b2b1Rpr/p2P3p/1ppB4/8/2B5/PP1q1PPP/2R3K1 w - - 0 1` (`Qq` should be replaced by `-` as neither White nor Black can queen-side castle).

**Comment by Mohankrish01** [comment]
Thanks a lot for your help. I hope I will see many new features in the plugin soon like Puzzles, multiple PGN games, connecting with Engine etc. It will be helpful for everyone.

We are already impressed with the plugin and we will not hesitate to buy a premium version if you plan to create one (with above features).
