### ISSUE TITLE
The analysis of the pgn file finds errors that do not exist

### ISSUE THREAD

**Issue by mishashap** [yo35/rpb-chessboard#88]
I created a pgn content, that I tried to use in 2 different ways:
1) directly including in the article text ----> it worked fine

2) creating a pgn file, that I adress through [pgn url="http....   "}. Here I adapted [fen]...[/fen] instructions to [FEN "...."] syntaxe. ----> the analysis of the file signals different errors:
   a) unrecognized character (for example in [FEN "rnbqkbnr/...."] the second r is unrecognised!!!)

   b) {1 d4 ....} is not treated as a comment and the error is: illegal move, you can not take your own piece.

Did I download the "good" version of the plugin? how to verify that I installed and activated the good one?

**Comment by yo35** [comment]
Same issue as #87 I guess?

**Comment by yo35** [comment]
Same as #87.
