### ISSUE TITLE
can't upload PGN file using wordpress media

### ISSUE THREAD

**Issue by Designershree** [yo35/rpb-chessboard#89]
hi,
i want to upload PGN file in wordpress using media...but 'Sorry, this file type is not permitted for security reasons.' this type of error genrated..so can u help me... what can i do....

**Comment by yo35** [comment]
Hi,
PGN uploading is supposed to be OK with RPB Chessboard version 4.7 (it does not work with previous versions).

If this is not the case, then:
- Check your version of WP. Issues related to file uploading has been reported with some recent WP versions (see https://tribulant.com/blog/wordpress/how-to-fix-sorry-this-file-type-is-not-permitted-for-security-reasons/ for instance). Currently, I'm using WP 4.7.4, and everything seems OK.
- Try to disable (temporarily) the other plugins and/or to change your theme, to be sure that this is not a conflict-like problem.
- Ultimately, try the `ALLOW_UNFILTERED_UPLOADS` solution described in https://tribulant.com/blog/wordpress/how-to-fix-sorry-this-file-type-is-not-permitted-for-security-reasons/. However, this should not be necessary as RPB Chessboard 4.7 automatically register PGN files in the list of authorized MIME types (i.e. the list of file types that are allowed to be uploaded).

**Comment by yo35** [comment]
No answer since April => I close the issue.
