### ISSUE TITLE
Autoplay control

### ISSUE THREAD

**Issue by fafamonge** [yo35/rpb-chessboard#91]
Hi Yo, I've looking in the posts something about the Autoplay button in the control panel to watch the games as TV mode. Additionally, I found the optional flip button very useful and I think it would be also a nice feature. 

You have done a great job with this plugin, congrats.

**Comment by yo35** [comment]
@shenky1 Sorry for the late reply.

The key thing is, I would like to have that feature added to the underlying lib, i.e. https://github.com/yo35/kokopu-react. I'll try to handle it soon.

**Comment by yo35** [comment]
Auto-play is available as of version 8.0.0 (just released).

**Comment by shenky1** [comment]
It looks very nice! Thanks! 👍
