### ISSUE TITLE
URL Attribute to download the PGN

### ISSUE THREAD

**Issue by fafamonge** [yo35/rpb-chessboard#92]
I have been testing the RPB, I realize that having an attribute called "download" I can put the URL of my Download Monitor (a solution for managing downloadable files, monitoring downloads and outputting download links and file information on WordPress) to share the PGN with visitors. 

As following:
[pgn url="http://www.ajedrez.life/media/database/monge-murillo_09042017.pgn" game=0 download="http://www.ajedrez.life/download/3382/"]

<img src="http://www.ajedrez.life/media/Captura-RPB.JPG"/>

With url as source of PGN and with download to monitoring the downloads of the file. Could be a feature request?

RM

**Comment by yo35** [comment]
This is obviously a relevant feature request! Already expressed as #78.

**Comment by yo35** [comment]
Done in version 5.0 (just released)

**Comment by fafamonge** [comment]
Hello Yoann,

I'm sending this because I love your work on this project. Can you include
my improvements to the plugin?

[image: image.png]
[image: image.png]

Name: Chess.com (But you could rename it as Fafamonge or Fafa if you want)
Dark Squares: #769656
Light Squares: #eeeed2

[image: image.png]
[image: image.png]

[image: image.png]

It would be an honor to appear in the credits.

It would be nice to have an Autoplay button.

Tell me how could I contribute translating to Spanish and Portuguese,
please let me know.

I'm looking the way (researching) to put a switch ON/OFF button to
Stockfish Analysis or instead maybe a link "Analize in Lichess" or "Analyze
in Chess.com" or "Analyze in Chess24". On my server is already running
FishNet, an script that provide game analysis for Lichess. Do you know
Niklas Fiekas?

Greetings,

RM
