### ISSUE TITLE
I not see the chessboard

### ISSUE THREAD

**Issue by italianplayer** [yo35/rpb-chessboard#94]
Hello
 I installed the rpbchess plugin 4.8.1 in my wordpress.
 I see the game but not the chessboard.
 I turned off all other plugins and changed themes.
 I still do not see the chessboard.
 Wordpress v.WordPress 4.3 theme Pinnacle
 http://wpdev2.altervista.org/rpbchess/

can you help me?

**Comment by yo35** [comment]
Hi,
From what I see by clicking on your link, everything seems to be OK:

![screenshot](https://user-images.githubusercontent.com/5740068/27986644-db3c457c-6401-11e7-954f-8ee23f4a5d98.png)

What do you mean exactly by "I see the game but not the chessboard"? Which browser are you using? (Chrome, Firefox, Internet Explorer... ?)

**Comment by italianplayer** [comment]
Hi,
the javascript chessboard with buttons for next and prev moves
all browser
example from web http://www.scstetten.schachvereine.de/test-rpb-chessboard-example/

**Comment by yo35** [comment]
Hi,
By default, a popup with the board appears when you click on the moves. You can change this this default behavior in the administration part of your website: menu "Chess" > "Settings" > "Position of the navigation board".

**Comment by italianplayer** [comment]
perfect! 
setting is now ok.
thanks
