### ISSUE TITLE
why the form of my game isn't right

### ISSUE THREAD

**Issue by maten2** [yo35/rpb-chessboard#95]
where is my mistake...please

i would like more blank space in the game

<img width="544" alt="capturehtml" src="https://user-images.githubusercontent.com/31878904/30311626-d01ec804-97c8-11e7-8866-012981c11492.PNG">
<img width="661" alt="capture" src="https://user-images.githubusercontent.com/31878904/30311628-d0e804b2-97c8-11e7-84d4-70ed3b8b5cb8.PNG">

**Comment by yo35** [comment]
Hi,
To get more space, you must let blank lines before comments and variations. For example, compare:

```
10.Bc2 {Prêt pour b4 ou d4} d5
```
versus:
```
10.Bc2
<blank line>
{Prêt pour b4 ou d4}
<blank line>
d5
```

Idem for variations:

```
17.Qg3 (17.Qxe7 Rbe8) 17...Bd6
```
versus:
```
17.Qg3
<blank line>
(17.Qxe7 Rbe8)
<blank line>
17...Bd6
```

**Comment by maten2** [comment]
oh thank you, i understand
