### ISSUE TITLE
RPB does not work in Wordpress Text widget

### ISSUE THREAD

**Issue by Willem-Platje** [yo35/rpb-chessboard#98]
Since version 5.0 the plug-in does not work anymore inside the Wordpress text-widget. The diagram does not show. Only the letters A-H en numbers 1-8 are shown in a long row under each other and then the moves are shown in a scrambled manner. All comments are also lost.

**Comment by yo35** [comment]
Hi,
Which plugin are you using to make the [fen]/[pgn] shortcodes work in the text widget? By default, shortcodes are not processed in text widgets.
Also, what is the address of your website?

**Comment by Willem-Platje** [comment]
Hi Yoann,

I know by default, shortcodes are not processed in text widgets. But it worked fine within the Wordpress Text (Tekst - Nl) widget until version 5.0.

This is the page where I use the tekst_widget in a Page-Builder row:
![page_partijen_intern](https://user-images.githubusercontent.com/32854900/31773464-28193ada-b4e3-11e7-8863-596b0bce350a.jpg)
When I open the tekst-widget you'll see the .pgn file:
![text_widget_wordpress](https://user-images.githubusercontent.com/32854900/31773517-4c8261b2-b4e3-11e7-864a-df050499b5c0.jpg)
The visitors of the website of the Chessclub "De Willige Dame" (www.dewilligedame.nl) will see this on their screens:
![page_with_games](https://user-images.githubusercontent.com/32854900/31773557-6c3b110c-b4e3-11e7-9cf8-9f12a54bdd2b.jpg)
By using the menu-items Ïntern" -> "Partijen" on the frontpage you reach the games that are played in the internal competitition:
![frontpage_intern_partijen games](https://user-images.githubusercontent.com/32854900/31773589-8157fba4-b4e3-11e7-8c95-638d85ace8dc.jpg)
Kind regards,
Wim Platje

**Comment by yo35** [comment]
Hi,
I could not find the WordPress plugin that brings this Wordpress Text (Tekst - Nl) widget. I've tried the [fen]/[pgn] shortcodes with [Enhanced Text Widget](https://wordpress.org/plugins/enhanced-text-widget/) instead, and it works fine.

I've had a look to the HTML code of the pages generated by your website, and there is something strange with the way CSS references appear in the pages. To be more precise, the website generates this:
```
<link rel='stylesheet' ...  href='http://.../css/rpbchess-ui-chessgame.css' />
```
while the plugin version number is supposed to be appended at the end of the URL, like this:
```
<link rel='stylesheet' ...  href='http://.../css/rpbchess-ui-chessgame.css?ver=5.1.1' />
```
The aim of the suffix is to force web browsers to re-download the CSS when a plugin version changes. (And by the way, this mechanism is not specific to RPB Chessboard, it is used by all WordPress plugins).

To conclude, my guess is that the CSS did not get properly refreshed in your web browser when you tried the upgrade from RPB Chessboard 4.8 to 5. You should retry, and force CSS to get refreshed from scratch by pressing <F5> several times in your web browser.

**Comment by Willem-Platje** [comment]
Hi Yoann,

Your reply solved the problem. My attention was drawn by you writing: "The aim of the suffix is to force web browsers to re-download the CSS when a plugin version changes."

It was apparently caused by a plugin I use to improve the loading speed of the website. A recommendation I found on Google pagespeed insights.

It is called: **Remove query strings from static resources** (like CSS & JS files to improve your scores in Pingdom, GTmetrix, PageSpeed and YSlow. Support and speed optimization available at Speed Up My Website. (https://www.speedupmywebsite.com/) )
![plugin causes update problems](https://user-images.githubusercontent.com/32854900/31885832-26e07d92-b7f2-11e7-9585-166d569e82da.jpg)

Apparently it caused the truncation of the versionnumber of the plugin at the end of the URL:

<link rel='stylesheet' ...  href='http://.../css/rpbchess-ui-chessgame.css' /> in stead of:
<link rel='stylesheet' ...  href='http://.../css/rpbchess-ui-chessgame.css?ver=5.1.1' />

I deactived this plugin and the update of RPB-Chessboard plugin went fine. Everything works OK. By the way:  I never experienced this plugin to cause problems while updating other plugins, but I'm glad this problem is solverd now. Thank you very much for your help!

Kind regards,
Wim Platje

**Comment by yo35** [comment]
If you want to get more details on why removing the version number from static resources may cause problem, you can have a look to the following article:
https://cometcache.com/kb-article/why-doesnt-comet-cache-remove-query-strings-from-static-resources/
